-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/12/2 9:41:45
-- Server version: 5.6.25-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Definition for table innodb_monitor
--
DROP TABLE IF EXISTS innodb_monitor;
CREATE TABLE innodb_monitor (
  a INT(11) DEFAULT NULL
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table r_clearmachine
--
DROP TABLE IF EXISTS r_clearmachine;
CREATE TABLE r_clearmachine (
  id INT(11) NOT NULL AUTO_INCREMENT,
  clearid VARCHAR(50) DEFAULT NULL,
  sdetailid VARCHAR(50) NOT NULL,
  orderid VARCHAR(50) NOT NULL,
  dishid VARCHAR(50) DEFAULT NULL,
  normalprice DECIMAL(10, 2) DEFAULT NULL,
  discountamount DECIMAL(10, 2) DEFAULT NULL,
  discountid VARCHAR(50) DEFAULT NULL,
  couponid VARCHAR(50) DEFAULT NULL,
  couponamount DECIMAL(10, 2) DEFAULT NULL,
  payamount DECIMAL(10, 2) DEFAULT NULL,
  couponNum INT(11) DEFAULT NULL,
  feeamount DECIMAL(10, 2) DEFAULT NULL,
  settledid VARCHAR(50) DEFAULT NULL,
  incometype INT(11) DEFAULT NULL,
  membercardno VARCHAR(50) DEFAULT NULL,
  bankcardno VARCHAR(50) DEFAULT NULL,
  opendate DATE DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  payway INT(11) DEFAULT NULL,
  cleardate DATETIME DEFAULT NULL,
  userid VARCHAR(50) DEFAULT NULL,
  workdate DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX UQ_r_clearmachine_clearid (clearid),
  INDEX UQ_r_clearmachine_sdetailid (userid, workdate)
)
ENGINE = INNODB
AUTO_INCREMENT = 82
AVG_ROW_LENGTH = 260
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table sequence
--
DROP TABLE IF EXISTS sequence;
CREATE TABLE sequence (
  name VARCHAR(20) NOT NULL,
  val INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (name)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_application
--
DROP TABLE IF EXISTS t_b_application;
CREATE TABLE t_b_application (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  name VARCHAR(32) DEFAULT NULL COMMENT '应用名称',
  type CHAR(2) DEFAULT NULL COMMENT '应用类型。01：web应用；02：pad应用',
  description VARCHAR(100) DEFAULT NULL COMMENT '描述',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  creator VARCHAR(50) DEFAULT NULL COMMENT '创建者',
  webroot VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_business
--
DROP TABLE IF EXISTS t_b_business;
CREATE TABLE t_b_business (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  user_id VARCHAR(50) DEFAULT NULL COMMENT '用户基本信息表id',
  province VARCHAR(50) DEFAULT NULL COMMENT '省',
  city VARCHAR(50) DEFAULT NULL COMMENT '市',
  region VARCHAR(50) DEFAULT NULL COMMENT '区',
  address VARCHAR(200) DEFAULT NULL COMMENT '详细地址',
  business_name VARCHAR(128) DEFAULT NULL COMMENT '企业名称',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  creator VARCHAR(50) DEFAULT NULL COMMENT '创建者',
  dbid VARCHAR(50) DEFAULT NULL COMMENT '数据库ID',
  tenantid VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_employee
--
DROP TABLE IF EXISTS t_b_employee;
CREATE TABLE t_b_employee (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  user_id VARCHAR(50) DEFAULT NULL COMMENT '用户基本信息id',
  sex CHAR(1) DEFAULT NULL COMMENT '性别。1：男；0：女',
  birthdate DATE DEFAULT NULL COMMENT '出生日期',
  payment_password VARCHAR(32) DEFAULT NULL,
  job_number CHAR(10) DEFAULT NULL COMMENT '员工工号。每个门店内唯一',
  position VARCHAR(30) DEFAULT NULL COMMENT '职位',
  home_address VARCHAR(200) DEFAULT NULL COMMENT '家庭住址',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  creator VARCHAR(50) DEFAULT NULL COMMENT '创建者',
  branch_id INT(11) DEFAULT NULL COMMENT '门店id',
  branch_name VARCHAR(255) DEFAULT NULL COMMENT '门店名',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_function
--
DROP TABLE IF EXISTS t_b_function;
CREATE TABLE t_b_function (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  name VARCHAR(50) DEFAULT NULL COMMENT '功能名',
  code VARCHAR(20) DEFAULT NULL COMMENT '功能编号',
  application VARCHAR(50) DEFAULT NULL COMMENT '所属应用',
  level INT(11) DEFAULT NULL COMMENT '功能级别',
  parent_fun VARCHAR(50) DEFAULT NULL COMMENT '上级功能',
  is_leaf TINYINT(1) DEFAULT NULL COMMENT '是否末级功能',
  operation_type CHAR(2) DEFAULT NULL COMMENT '操作类型。01：查询；02：新增；03：修改；04：删除',
  status CHAR(12) DEFAULT NULL COMMENT '状态',
  description VARCHAR(100) DEFAULT NULL COMMENT '功能描述',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  creator VARCHAR(50) DEFAULT NULL COMMENT '创建用户id',
  scope_code CHAR(2) DEFAULT NULL COMMENT '作用范围编码',
  scope_name VARCHAR(30) DEFAULT NULL COMMENT '作用范围名称',
  `index` INT(11) DEFAULT NULL COMMENT '序号',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统功能';

--
-- Definition for table t_b_function_url
--
DROP TABLE IF EXISTS t_b_function_url;
CREATE TABLE t_b_function_url (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  `function` VARCHAR(50) DEFAULT NULL COMMENT '功能id',
  url VARCHAR(50) DEFAULT NULL COMMENT 'urlid',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '功能与url映射表';

--
-- Definition for table t_b_headquarter_user
--
DROP TABLE IF EXISTS t_b_headquarter_user;
CREATE TABLE t_b_headquarter_user (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  user_id VARCHAR(50) DEFAULT NULL COMMENT '用户基本信息表id'
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_role
--
DROP TABLE IF EXISTS t_b_role;
CREATE TABLE t_b_role (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  code VARCHAR(32) DEFAULT NULL COMMENT '角色编码',
  name VARCHAR(32) DEFAULT NULL COMMENT '角色名称',
  type CHAR(2) DEFAULT NULL COMMENT '角色类型。01：系统内置；02： 用户定义',
  scope_code CHAR(2) DEFAULT NULL COMMENT '作用范围编码',
  scope_name VARCHAR(30) DEFAULT NULL COMMENT '作用范围名称',
  status CHAR(2) DEFAULT NULL COMMENT '状态',
  description VARCHAR(100) DEFAULT NULL COMMENT '角色描述',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  creator VARCHAR(50) DEFAULT NULL COMMENT '创建者',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_role_branch
--
DROP TABLE IF EXISTS t_b_role_branch;
CREATE TABLE t_b_role_branch (
  id VARCHAR(50) NOT NULL,
  role VARCHAR(50) DEFAULT NULL,
  branch_name VARCHAR(255) DEFAULT NULL COMMENT '门店名',
  branch_id INT(11) DEFAULT NULL COMMENT '门店id',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_role_function
--
DROP TABLE IF EXISTS t_b_role_function;
CREATE TABLE t_b_role_function (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  role VARCHAR(50) DEFAULT NULL COMMENT '角色id',
  `function` VARCHAR(50) DEFAULT NULL COMMENT '功能id',
  role_name VARCHAR(32) DEFAULT NULL COMMENT '角色名',
  function_name VARCHAR(50) DEFAULT NULL COMMENT '功能名',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_scope_dict
--
DROP TABLE IF EXISTS t_b_scope_dict;
CREATE TABLE t_b_scope_dict (
  code CHAR(2) NOT NULL COMMENT '作用范围编码。',
  name VARCHAR(30) DEFAULT NULL COMMENT '作用范围名称。',
  PRIMARY KEY (code)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_url
--
DROP TABLE IF EXISTS t_b_url;
CREATE TABLE t_b_url (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  name VARCHAR(50) DEFAULT NULL COMMENT 'url名称',
  url VARCHAR(256) DEFAULT NULL COMMENT 'url地址',
  type CHAR(2) DEFAULT NULL COMMENT 'url类型。01：查询；02：新增；03：修改；04：删除',
  description VARCHAR(100) DEFAULT NULL COMMENT '描述',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  creator VARCHAR(50) DEFAULT NULL COMMENT '创建者',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_user
--
DROP TABLE IF EXISTS t_b_user;
CREATE TABLE t_b_user (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  account VARCHAR(32) DEFAULT NULL COMMENT '自动创建的账号',
  `password` VARCHAR(32) DEFAULT NULL COMMENT '密码',
  name VARCHAR(32) DEFAULT NULL COMMENT '姓名',
  status CHAR(2) DEFAULT NULL COMMENT '账号状态',
  mobile CHAR(11) DEFAULT NULL COMMENT '手机',
  area_code CHAR(4) DEFAULT NULL COMMENT '固定电话区号',
  telephone CHAR(8) DEFAULT NULL COMMENT '固定电话',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  creator VARCHAR(50) DEFAULT NULL COMMENT '创建者',
  email VARCHAR(200) DEFAULT NULL,
  user_type CHAR(2) DEFAULT NULL COMMENT '用户类型',
  order_num INT(11) DEFAULT NULL,
  lastlogintime TIMESTAMP NULL DEFAULT NULL COMMENT '最后登录时间',
  tenantid VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_user_branch
--
DROP TABLE IF EXISTS t_b_user_branch;
CREATE TABLE t_b_user_branch (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  user_id VARCHAR(50) DEFAULT NULL COMMENT '用户id',
  branch_id INT(11) DEFAULT NULL COMMENT '门店id',
  branch_name VARCHAR(255) DEFAULT NULL COMMENT '门店名',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_user_role
--
DROP TABLE IF EXISTS t_b_user_role;
CREATE TABLE t_b_user_role (
  id VARCHAR(50) NOT NULL COMMENT 'id',
  user_id VARCHAR(50) DEFAULT NULL COMMENT '用户基本信息id',
  role_id VARCHAR(50) DEFAULT NULL COMMENT '角色id',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_b_user_security_level
--
DROP TABLE IF EXISTS t_b_user_security_level;
CREATE TABLE t_b_user_security_level (
  id VARCHAR(50) NOT NULL COMMENT 'id，等于用户id',
  set_password TINYINT(1) DEFAULT NULL COMMENT '是否设置密码',
  verify_email TINYINT(1) DEFAULT NULL COMMENT '是否验证邮箱',
  bind_mobile TINYINT(1) DEFAULT NULL COMMENT '是否绑定手机',
  score INT(3) DEFAULT NULL COMMENT '安全等级得分',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_basicdata
--
DROP TABLE IF EXISTS t_basicdata;
CREATE TABLE t_basicdata (
  id VARCHAR(50) NOT NULL COMMENT '主键',
  itemid VARCHAR(50) NOT NULL COMMENT '编号',
  itemDesc VARCHAR(200) NOT NULL COMMENT '名称',
  isShow TINYINT(4) DEFAULT NULL,
  itemSort INT(11) DEFAULT NULL COMMENT '排序',
  status INT(11) NOT NULL COMMENT '1：有效  0：无效',
  fid VARCHAR(50) NOT NULL COMMENT '父id',
  depthnum INT(20) NOT NULL COMMENT '深度（第一级，第二级）',
  itemType VARCHAR(50) NOT NULL COMMENT '字典类型（菜单，用户学历）',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  remark CHAR(100) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_biz_log
--
DROP TABLE IF EXISTS t_biz_log;
CREATE TABLE t_biz_log (
  id VARCHAR(255) NOT NULL,
  tenantid VARCHAR(30) DEFAULT NULL COMMENT '租户id',
  syn_status INT(2) DEFAULT NULL COMMENT '同步状态 0 未同步 1 已同步',
  inserttime DATETIME DEFAULT NULL COMMENT '插入日期',
  branchid VARCHAR(30) DEFAULT NULL COMMENT '分店id',
  open_date DATETIME DEFAULT NULL COMMENT '开业日期',
  end_date DATETIME DEFAULT NULL COMMENT '结业日期',
  open_user VARCHAR(20) DEFAULT NULL COMMENT '开业人',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 682
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_branch
--
DROP TABLE IF EXISTS t_branch;
CREATE TABLE t_branch (
  branchid INT(11) NOT NULL AUTO_INCREMENT COMMENT '分店id',
  branchname VARCHAR(255) DEFAULT NULL COMMENT '分店名称',
  branchnamepingying VARCHAR(200) DEFAULT NULL COMMENT '店名全拼',
  branchnamepyfirstchar VARCHAR(200) DEFAULT NULL COMMENT '店名拼音首字母',
  tenantid INT(11) DEFAULT NULL COMMENT '所属商户id',
  province VARCHAR(50) DEFAULT NULL,
  city VARCHAR(50) DEFAULT NULL,
  region VARCHAR(50) DEFAULT NULL,
  addresscitycode VARCHAR(500) DEFAULT NULL COMMENT '分店地址城市编码',
  addressdetail VARCHAR(255) DEFAULT NULL COMMENT '分店详细地址',
  manager VARCHAR(255) DEFAULT NULL COMMENT '店长',
  cellphone VARCHAR(50) DEFAULT NULL COMMENT '手机',
  telphone VARCHAR(50) DEFAULT NULL COMMENT '座机',
  taxphone VARCHAR(50) DEFAULT NULL COMMENT '传真号码',
  contact1 VARCHAR(50) DEFAULT NULL COMMENT '联系人1',
  contact1_tel VARCHAR(50) DEFAULT NULL COMMENT '联系人1电话号码',
  contact2 VARCHAR(50) DEFAULT NULL COMMENT '联系人2',
  contact2_tel VARCHAR(50) DEFAULT NULL COMMENT '联系人2电话号码',
  status INT(11) DEFAULT 0,
  generatetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (branchid)
)
ENGINE = INNODB
AUTO_INCREMENT = 287166
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_branch_biz_log
--
DROP TABLE IF EXISTS t_branch_biz_log;
CREATE TABLE t_branch_biz_log (
  id VARCHAR(50) NOT NULL,
  opendate DATETIME DEFAULT NULL,
  enddate DATETIME DEFAULT NULL,
  branchid VARCHAR(20) DEFAULT NULL,
  openuser VARCHAR(20) DEFAULT NULL,
  enduser VARCHAR(20) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL COMMENT '每个分店的开业，结业记录',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_branch_code
--
DROP TABLE IF EXISTS t_branch_code;
CREATE TABLE t_branch_code (
  id VARCHAR(50) NOT NULL,
  branch_id VARCHAR(100) NOT NULL,
  branch_name VARCHAR(200) NOT NULL,
  status VARCHAR(10) NOT NULL,
  inserttime DATETIME NOT NULL,
  branch_id_code VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_branch_dish_code
--
DROP TABLE IF EXISTS t_branch_dish_code;
CREATE TABLE t_branch_dish_code (
  id VARCHAR(50) NOT NULL,
  dish_id VARCHAR(100) NOT NULL,
  dish_name VARCHAR(100) NOT NULL,
  jde_code VARCHAR(50) NOT NULL,
  unit VARCHAR(50) NOT NULL,
  status VARCHAR(10) NOT NULL,
  inserttime DATETIME NOT NULL,
  unitchar VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_branch_info
--
DROP TABLE IF EXISTS t_branch_info;
CREATE TABLE t_branch_info (
  id VARCHAR(50) NOT NULL,
  branchcode VARCHAR(255) DEFAULT NULL COMMENT '分店编码',
  branchid VARCHAR(50) DEFAULT NULL COMMENT '分店id',
  branchname VARCHAR(255) DEFAULT NULL COMMENT '分店名称',
  branchaddress VARCHAR(255) DEFAULT NULL COMMENT '分店地址',
  managerid VARCHAR(50) DEFAULT NULL COMMENT '分店经理id',
  managername VARCHAR(50) DEFAULT NULL COMMENT '分店经理',
  managertel VARCHAR(50) DEFAULT NULL COMMENT '分店联系电话',
  serverversion VARCHAR(50) DEFAULT NULL COMMENT '分店服务器版本',
  padversion VARCHAR(255) DEFAULT NULL COMMENT '分店PAD版本',
  insertime DATETIME DEFAULT NULL COMMENT '插入日期',
  updatetime DATETIME DEFAULT NULL COMMENT '更新日期',
  tenantid VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_business_report
--
DROP TABLE IF EXISTS t_business_report;
CREATE TABLE t_business_report (
  Susinessid INT(11) NOT NULL AUTO_INCREMENT,
  Shouldamount DECIMAL(10, 2) DEFAULT NULL,
  Paidinamount DECIMAL(10, 2) DEFAULT NULL,
  Discountamount DECIMAL(10, 2) DEFAULT NULL,
  Discount DECIMAL(10, 2) DEFAULT NULL,
  Money DECIMAL(10, 2) DEFAULT NULL,
  Card DECIMAL(10, 2) DEFAULT NULL,
  ICBC DECIMAL(10, 2) DEFAULT NULL,
  otherbank DECIMAL(10, 2) DEFAULT NULL,
  Merbervaluenet DECIMAL(10, 2) DEFAULT NULL,
  Total DECIMAL(10, 2) DEFAULT NULL,
  MeberTicket DECIMAL(10, 2) DEFAULT NULL,
  Integralconsum DECIMAL(10, 2) DEFAULT NULL,
  Mebervalueadd DECIMAL(10, 2) DEFAULT NULL,
  Mebercousumcollet DECIMAL(10, 2) DEFAULT NULL,
  Tablenum DECIMAL(10, 2) DEFAULT NULL,
  Settlementnum DECIMAL(10, 2) DEFAULT NULL,
  Avgconsumtime DECIMAL(10, 2) DEFAULT NULL,
  Attendance DECIMAL(10, 2) DEFAULT NULL,
  Shouldaverage DECIMAL(10, 2) DEFAULT NULL,
  Paidinaverage DECIMAL(10, 2) DEFAULT NULL,
  tableconsumption DECIMAL(10, 2) DEFAULT NULL,
  Overtaiwan DECIMAL(10, 2) DEFAULT NULL,
  Bastfree DECIMAL(10, 2) DEFAULT NULL,
  Malingincom DECIMAL(10, 2) DEFAULT NULL,
  Discountmoney DECIMAL(10, 2) DEFAULT NULL,
  Statistictime DATE DEFAULT NULL,
  Datetype VARCHAR(10) DEFAULT NULL,
  createdDate DATETIME DEFAULT NULL,
  PRIMARY KEY (Susinessid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_complaint_type
--
DROP TABLE IF EXISTS t_complaint_type;
CREATE TABLE t_complaint_type (
  complaint_id VARCHAR(50) DEFAULT NULL,
  complaint_type_id VARCHAR(10) DEFAULT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 712
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_coupon_rule
--
DROP TABLE IF EXISTS t_coupon_rule;
CREATE TABLE t_coupon_rule (
  ruleid VARCHAR(50) NOT NULL COMMENT '主键 ',
  couponid VARCHAR(50) NOT NULL COMMENT '优惠表的主键',
  dishid VARCHAR(50) DEFAULT NULL COMMENT '菜品id',
  dishnum INT(11) DEFAULT NULL COMMENT '满足菜品的份数',
  freedishid VARCHAR(50) DEFAULT NULL COMMENT '免费的菜品id',
  freedishnum INT(11) DEFAULT NULL COMMENT '免费的菜品数量',
  couponway INT(11) DEFAULT NULL COMMENT '优惠方式',
  comsumeway INT(11) DEFAULT NULL,
  couponrate DECIMAL(10, 2) DEFAULT NULL COMMENT '打折比率',
  couponamount DECIMAL(10, 2) DEFAULT NULL COMMENT '打折金额',
  totalamount DECIMAL(10, 2) DEFAULT NULL COMMENT '整单金额',
  couponcash DECIMAL(10, 2) DEFAULT NULL COMMENT '赠送代金券金额',
  couponnum INT(11) DEFAULT NULL COMMENT '可使用代金券数量',
  freeamount DECIMAL(10, 2) DEFAULT NULL COMMENT '代金券每张抵用金额',
  banktype VARCHAR(50) DEFAULT NULL COMMENT '银行类型',
  partnername VARCHAR(200) DEFAULT NULL COMMENT '合作单位',
  groupweb VARCHAR(50) DEFAULT NULL COMMENT '团购网站',
  unitid VARCHAR(50) DEFAULT NULL COMMENT '计量单位',
  debitamount DECIMAL(10, 2) DEFAULT NULL,
  PRIMARY KEY (ruleid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_coupons
--
DROP TABLE IF EXISTS t_coupons;
CREATE TABLE t_coupons (
  couponid VARCHAR(50) NOT NULL COMMENT '主键',
  couponparent VARCHAR(100) DEFAULT NULL COMMENT '优惠类型',
  couponchild VARCHAR(100) DEFAULT NULL COMMENT '子优惠类型',
  showposition INT(2) DEFAULT NULL COMMENT '0 PAD端 1 POS 端',
  couponcustomer INT(2) DEFAULT NULL COMMENT '优惠对象 0 所有顾客 1 仅限会员',
  couponname VARCHAR(100) DEFAULT NULL COMMENT '优惠名称',
  description VARCHAR(50) DEFAULT NULL COMMENT '活动简介',
  totalamount DECIMAL(10, 2) DEFAULT NULL COMMENT '整单 满金额',
  couponperiod VARCHAR(200) DEFAULT NULL COMMENT '间隔  每周 1,3,5 每月 12,13,15',
  coupontype INT(2) DEFAULT NULL COMMENT '0 每天 1 每周2 每月',
  begintime DATETIME DEFAULT NULL,
  endtime DATETIME DEFAULT NULL,
  userid VARCHAR(50) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL,
  status INT(11) DEFAULT NULL COMMENT '是否可用',
  wholesingle VARCHAR(2) DEFAULT NULL COMMENT '0 整单  1 单品',
  ruledescription VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (couponid),
  UNIQUE INDEX UQ_t_coupons_couponid (couponid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_dictionary
--
DROP TABLE IF EXISTS t_dictionary;
CREATE TABLE t_dictionary (
  dictid VARCHAR(50) NOT NULL,
  itemid VARCHAR(50) DEFAULT NULL,
  itemDesc VARCHAR(50) DEFAULT NULL,
  itemSort INT(11) DEFAULT NULL,
  status INT(11) DEFAULT NULL,
  type VARCHAR(50) DEFAULT NULL,
  typename VARCHAR(50) NOT NULL,
  begin_time VARCHAR(20) DEFAULT NULL,
  end_time VARCHAR(20) DEFAULT NULL,
  charges_status VARCHAR(5) DEFAULT NULL,
  member_price VARCHAR(10) DEFAULT NULL,
  price VARCHAR(10) DEFAULT NULL,
  date_type VARCHAR(5) DEFAULT NULL,
  item_value VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (dictid),
  UNIQUE INDEX UQ_t_dictionary_dictid (dictid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_discount
--
DROP TABLE IF EXISTS t_discount;
CREATE TABLE t_discount (
  discountId VARCHAR(50) NOT NULL,
  dishid VARCHAR(50) NOT NULL,
  status INT(11) NOT NULL,
  begintime DATETIME DEFAULT NULL,
  endtime DATETIME DEFAULT NULL,
  createuserid VARCHAR(50) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL,
  updatetime DATETIME DEFAULT NULL,
  discountamount DECIMAL(10, 2) DEFAULT NULL,
  discountrate DECIMAL(10, 2) DEFAULT NULL,
  discounttype INT(11) DEFAULT NULL,
  PRIMARY KEY (discountId),
  UNIQUE INDEX UQ_t_discount_discountId (discountId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_dish
--
DROP TABLE IF EXISTS t_dish;
CREATE TABLE t_dish (
  dishid VARCHAR(50) NOT NULL,
  dishNo VARCHAR(50) DEFAULT NULL,
  columnId VARCHAR(500) DEFAULT NULL,
  userId VARCHAR(50) DEFAULT NULL,
  title varchar(300) DEFAULT NULL COMMENT '菜品名称',
  label VARCHAR(50) DEFAULT NULL,
  introduction varchar(800) DEFAULT NULL COMMENT '菜品简介',
  `source` VARCHAR(50) DEFAULT NULL,
  author VARCHAR(50) DEFAULT NULL,
  image VARCHAR(200) DEFAULT NULL,
  imagetitle VARCHAR(200) DEFAULT NULL,
  content VARCHAR(200) DEFAULT NULL,
  isDisplay INT(11) DEFAULT NULL,
  isHead INT(11) DEFAULT NULL,
  headSort INT(11) DEFAULT NULL,
  isSelect INT(11) DEFAULT NULL,
  createTime DATETIME DEFAULT NULL,
  releaseTime DATETIME DEFAULT NULL,
  modifyTime DATETIME DEFAULT NULL,
  status INT(11) DEFAULT NULL,
  vipprice VARCHAR(100) DEFAULT NULL,
  price VARCHAR(100) DEFAULT NULL,
  level VARCHAR(50) DEFAULT NULL,
  printer VARCHAR(50) DEFAULT NULL,
  unit VARCHAR(300) DEFAULT NULL COMMENT '菜品单位',
  abbrdesc VARCHAR(50) DEFAULT NULL,
  dishtype INT(11) DEFAULT NULL,
  orderNum INT(11) DEFAULT NULL,
  imageWidth INT(10) DEFAULT NULL,
  imageHeight INT(10) DEFAULT NULL,
  recommend INT(4) DEFAULT 0,
  weigh INT(4) DEFAULT 0,
  py VARCHAR(500) DEFAULT NULL,
  cantakeout varchar(2) NOT NULL DEFAULT b'0',
  PRIMARY KEY (dishid),
  UNIQUE INDEX UQ_t_dish_dishid (dishid)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 421
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_dish_cal_factor_temp
--
DROP TABLE IF EXISTS t_dish_cal_factor_temp;
CREATE TABLE t_dish_cal_factor_temp (
  id INT(5) NOT NULL AUTO_INCREMENT,
  couponid VARCHAR(100) DEFAULT NULL,
  coupondetailid VARCHAR(255) NOT NULL,
  couponname VARCHAR(100) DEFAULT NULL,
  caltype INT(2) DEFAULT NULL COMMENT '0 单品 1 双拼锅 2 除单品 3 分类 4 除分类 5 整单',
  dishtype INT(2) DEFAULT NULL,
  dishid VARCHAR(5000) DEFAULT NULL,
  columnid VARCHAR(5000) DEFAULT NULL,
  dishnum INT(10) DEFAULT NULL COMMENT '数量',
  status INT(2) DEFAULT 0 COMMENT '0 有效1 无效',
  PRIMARY KEY (id),
  UNIQUE INDEX coupondetailid (coupondetailid)
)
ENGINE = INNODB
AUTO_INCREMENT = 141
AVG_ROW_LENGTH = 353
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_dish_dishtype
--
DROP TABLE IF EXISTS t_dish_dishtype;
CREATE TABLE t_dish_dishtype (
  id VARCHAR(50) NOT NULL DEFAULT '',
  columnid VARCHAR(50) DEFAULT NULL COMMENT '分类id',
  dishid VARCHAR(50) DEFAULT NULL COMMENT '菜品id',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 227
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '菜品和分类的关系表，用来解决一个菜品属于多个分类的情况';

--
-- Definition for table t_dish_group
--
DROP TABLE IF EXISTS t_dish_group;
CREATE TABLE t_dish_group (
  id VARCHAR(50) NOT NULL COMMENT '主键',
  dishid VARCHAR(50) DEFAULT NULL COMMENT '菜品主键',
  status INT(3) DEFAULT NULL COMMENT '主键 0 有效 1 无效',
  insertime DATETIME DEFAULT NULL COMMENT '插入时间',
  insertuserid VARCHAR(30) DEFAULT NULL COMMENT '插入人员',
  ordernum INT(10) DEFAULT NULL COMMENT '排序字段',
  selecttype VARCHAR(255) DEFAULT NULL COMMENT '分组是否是必选  0是必选1是自主选择',
  columnid VARCHAR(50) DEFAULT NULL COMMENT '菜品分类id',
  startnum INT(11) DEFAULT NULL COMMENT '从最大开始选   5-2 表示 5选2 填写 5',
  endnum INT(11) DEFAULT NULL COMMENT '从几选几 最后数字  5-2 填写 2 ',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_dish_set
--
DROP TABLE IF EXISTS t_dish_set;
CREATE TABLE t_dish_set (
  id VARCHAR(50) NOT NULL,
  masterdishid VARCHAR(50) NOT NULL,
  slavedishid VARCHAR(50) DEFAULT NULL COMMENT '可能有多个',
  slavedishprice DECIMAL(10, 2) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL,
  insertuserid VARCHAR(50) DEFAULT NULL,
  abbrdesc VARCHAR(50) DEFAULT NULL COMMENT '描述',
  status TINYINT(4) DEFAULT NULL COMMENT '标识（0是组合菜 1是套餐组合）',
  PRIMARY KEY (id),
  UNIQUE INDEX UQ_t_dish_set_id (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_dish_type
--
DROP TABLE IF EXISTS t_dish_type;
CREATE TABLE t_dish_type (
  dishid INT(11) DEFAULT NULL COMMENT '菜品id',
  priceid INT(11) DEFAULT NULL COMMENT '菜品价格主键',
  pricename VARCHAR(255) DEFAULT NULL COMMENT '价格名称',
  begindate DATETIME DEFAULT NULL COMMENT '开始日期',
  enddate DATETIME DEFAULT NULL COMMENT '结束日期',
  status INT(2) DEFAULT NULL COMMENT '状态',
  pricetype INT(3) DEFAULT NULL COMMENT '价格类型',
  pricedesc VARCHAR(255) DEFAULT NULL COMMENT '价格描述'
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_dish_unit
--
DROP TABLE IF EXISTS t_dish_unit;
CREATE TABLE t_dish_unit (
  id VARCHAR(50) NOT NULL COMMENT '主键',
  dishid VARCHAR(50) DEFAULT NULL,
  unit varchar(100) DEFAULT NULL COMMENT '菜品单位',
  price DECIMAL(10, 2) DEFAULT NULL,
  vipprice DECIMAL(10, 2) DEFAULT NULL,
  status INT(11) DEFAULT NULL,
  orderNum INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 236
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_gift
--
DROP TABLE IF EXISTS t_gift;
CREATE TABLE t_gift (
  id VARCHAR(50) NOT NULL,
  gift_no VARCHAR(50) DEFAULT NULL,
  gift_type_id VARCHAR(50) DEFAULT NULL,
  gift_name VARCHAR(300) DEFAULT NULL,
  gift_unit VARCHAR(100) DEFAULT NULL,
  gift_price DECIMAL(10, 2) DEFAULT NULL,
  member_price DECIMAL(10, 2) DEFAULT NULL,
  image_url VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1638
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_gift_log
--
DROP TABLE IF EXISTS t_gift_log;
CREATE TABLE t_gift_log (
  id VARCHAR(50) NOT NULL,
  gift_id VARCHAR(50) DEFAULT NULL,
  gift_type_id VARCHAR(50) DEFAULT NULL,
  give_table_no VARCHAR(50) DEFAULT NULL,
  receive_table_no VARCHAR(50) DEFAULT NULL,
  gift_no VARCHAR(50) DEFAULT NULL,
  gift_status CHAR(1) DEFAULT NULL,
  order_id VARCHAR(50) DEFAULT NULL,
  insert_time DATETIME DEFAULT NULL,
  gift_name VARCHAR(300) DEFAULT NULL,
  gift_num INT(4) DEFAULT NULL,
  gift_unit VARCHAR(10) DEFAULT NULL,
  gift_price DECIMAL(10, 2) DEFAULT NULL,
  gift_amount DECIMAL(10, 2) DEFAULT NULL,
  is_anonymous CHAR(1) DEFAULT NULL,
  receive_orderid VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_gift_type
--
DROP TABLE IF EXISTS t_gift_type;
CREATE TABLE t_gift_type (
  id VARCHAR(50) NOT NULL,
  gift_type CHAR(1) NOT NULL,
  gift_type_name VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_group_detail
--
DROP TABLE IF EXISTS t_group_detail;
CREATE TABLE t_group_detail (
  id VARCHAR(50) NOT NULL COMMENT '主键',
  groupid VARCHAR(50) DEFAULT NULL COMMENT '对应的t_group.id ',
  contactdishid VARCHAR(50) DEFAULT NULL COMMENT '关联的菜品id',
  inserttime DATETIME DEFAULT NULL COMMENT '插入时间',
  insertuserid VARCHAR(50) DEFAULT NULL COMMENT '插入人员',
  ordernum INT(10) DEFAULT NULL COMMENT '排序字段',
  status INT(3) DEFAULT NULL COMMENT '状态 0 必选 1 可选',
  dishunitid VARCHAR(100) DEFAULT NULL COMMENT '菜品计量单位',
  dishnum INT(11) DEFAULT NULL COMMENT '数量',
  dishid VARCHAR(50) DEFAULT NULL COMMENT '套餐的id',
  dishtype INT(4) DEFAULT NULL COMMENT '0单品 1火锅 2套餐',
  ispot INT(4) DEFAULT 0 COMMENT '0鱼  1是锅底',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_instrument
--
DROP TABLE IF EXISTS t_instrument;
CREATE TABLE t_instrument (
  id VARCHAR(50) NOT NULL DEFAULT '',
  instrument_name VARCHAR(50) DEFAULT NULL,
  instrument_code VARCHAR(50) DEFAULT NULL,
  msg_id VARCHAR(50) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_invoice
--
DROP TABLE IF EXISTS t_invoice;
CREATE TABLE t_invoice (
  id VARCHAR(50) NOT NULL DEFAULT '',
  cardno VARCHAR(50) DEFAULT NULL,
  device_no VARCHAR(30) DEFAULT NULL,
  invoice_title VARCHAR(100) DEFAULT NULL,
  remark1 VARCHAR(50) DEFAULT NULL,
  remark2 VARCHAR(50) DEFAULT NULL,
  remark3 VARCHAR(50) DEFAULT NULL,
  remark4 VARCHAR(50) DEFAULT NULL,
  invoice_amount DECIMAL(7, 2) DEFAULT NULL,
  orderid VARCHAR(50) DEFAULT NULL,
  status INT(2) DEFAULT NULL,
  invoiceType INT(2) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL,
  modifytime DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1024
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_item_report
--
DROP TABLE IF EXISTS t_item_report;
CREATE TABLE t_item_report (
  item_id_num INT(11) NOT NULL AUTO_INCREMENT,
  category VARCHAR(100) DEFAULT NULL,
  date_type VARCHAR(2) DEFAULT NULL,
  item_id VARCHAR(100) DEFAULT NULL,
  item_desc VARCHAR(200) DEFAULT NULL,
  num INT(11) DEFAULT NULL,
  share DECIMAL(10, 2) DEFAULT NULL,
  statistic_date DATE DEFAULT NULL,
  created_date DATETIME DEFAULT NULL,
  PRIMARY KEY (item_id_num)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_json_record
--
DROP TABLE IF EXISTS t_json_record;
CREATE TABLE t_json_record (
  id INT(11) NOT NULL AUTO_INCREMENT,
  json MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  inserttime TIMESTAMP NULL DEFAULT NULL,
  padpath VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1545
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_menu
--
DROP TABLE IF EXISTS t_menu;
CREATE TABLE t_menu (
  menuid VARCHAR(50) NOT NULL COMMENT '菜谱id',
  menuname VARCHAR(500) DEFAULT NULL COMMENT '菜谱名称',
  effecttime DATETIME DEFAULT NULL COMMENT '启用时间',
  status INT(4) DEFAULT 0 COMMENT '菜谱状态（0未启用,1已启用,2定时启用,3删除）',
  createuserid VARCHAR(50) DEFAULT NULL COMMENT '创建者id',
  createtime DATETIME DEFAULT NULL COMMENT '创建时间',
  sortnum INT(11) DEFAULT NULL COMMENT '排序',
  PRIMARY KEY (menuid)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1092
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_menu_branch
--
DROP TABLE IF EXISTS t_menu_branch;
CREATE TABLE t_menu_branch (
  id VARCHAR(50) NOT NULL DEFAULT '',
  menuid VARCHAR(50) DEFAULT NULL,
  branchid INT(11) DEFAULT NULL COMMENT '分店id',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 963
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_message
--
DROP TABLE IF EXISTS t_message;
CREATE TABLE t_message (
  id VARCHAR(50) NOT NULL DEFAULT '',
  msg_type VARCHAR(10) DEFAULT NULL COMMENT '0 纸巾，1 加水，2 买单，3 呼叫',
  inserttime DATETIME DEFAULT NULL,
  status INT(11) DEFAULT NULL COMMENT '0 正常 1 错误',
  reply_time DATETIME DEFAULT NULL COMMENT '相应时间',
  sent_time DATETIME DEFAULT NULL COMMENT '发送手环的时间',
  tableno VARCHAR(10) DEFAULT NULL,
  userid VARCHAR(50) DEFAULT NULL,
  orderid VARCHAR(50) DEFAULT NULL,
  device_type VARCHAR(50) DEFAULT NULL,
  device_no VARCHAR(50) DEFAULT NULL,
  call_start_time DATETIME DEFAULT NULL,
  timeout_start_time DATETIME DEFAULT NULL,
  timeout_duration INT(11) DEFAULT NULL,
  call_status VARCHAR(10) DEFAULT NULL,
  call_nums INT(11) DEFAULT NULL,
  urge_nums INT(11) DEFAULT NULL,
  response_nums INT(11) DEFAULT NULL,
  call_over_date DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 247
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_nodeclass
--
DROP TABLE IF EXISTS t_nodeclass;
CREATE TABLE t_nodeclass (
  id INT(11) NOT NULL AUTO_INCREMENT,
  classNo VARCHAR(50) DEFAULT NULL COMMENT '结单编号',
  posID VARCHAR(50) DEFAULT NULL COMMENT 'POS id',
  operatorID VARCHAR(30) DEFAULT NULL COMMENT '操作员ID',
  operatorName VARCHAR(50) DEFAULT NULL COMMENT '操作员姓名',
  vIn DATETIME DEFAULT NULL COMMENT '签到时间',
  vOut DATETIME DEFAULT NULL COMMENT '签退时间',
  prettyCash DECIMAL(8, 2) DEFAULT 0.00 COMMENT '备用金',
  lastNonTable INT(11) DEFAULT NULL COMMENT '前班未结台数',
  lastNonDeposit DECIMAL(8, 2) DEFAULT 0.00 COMMENT '前班未结押金',
  tBeginPeople INT(11) DEFAULT NULL COMMENT '本班开单人数',
  tBeginTableTotal INT(11) DEFAULT NULL COMMENT '本班开台总数',
  tNonClosingTable INT(11) DEFAULT NULL COMMENT '本班未结台数',
  tNonClosingMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本班未结金额',
  tNonClosingDeposit DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本班未退押金',
  tClosingTable INT(11) DEFAULT NULL COMMENT '本班已结台数',
  tClosingPeople INT(11) DEFAULT NULL COMMENT '本班已结人数',
  tPresentedMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本班赠单金额',
  tRFoodMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本班退菜金额',
  itemMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '品项消费',
  serviceMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '服务费',
  roomMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '包房费',
  lowConsComp DECIMAL(8, 2) DEFAULT 0.00 COMMENT '最低消费补齐',
  preferenceMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '优惠金额',
  accountsReceivableSubtotal DECIMAL(8, 2) DEFAULT 0.00 COMMENT '应收小计',
  removeMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '抹零金额',
  ratedPreferenceMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '定额优惠金额',
  accountsReceivableTotal DECIMAL(8, 2) DEFAULT 0.00 COMMENT '应收合计',
  includedMoneyTotal DECIMAL(8, 2) DEFAULT 0.00 COMMENT '计入收入合计',
  noIncludedMoneyTotal DECIMAL(8, 2) DEFAULT 0.00 COMMENT '不计入收入合计',
  TotalMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '合计',
  tableware DECIMAL(8, 2) DEFAULT 0.00 COMMENT '餐具',
  drinks DECIMAL(8, 2) DEFAULT 0.00 COMMENT '酒水',
  drinksSmokeNoodle DECIMAL(8, 2) DEFAULT 0.00 COMMENT '酒水烟汤面',
  todayTurnover DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本日营业总额',
  priterTime DATETIME DEFAULT NULL COMMENT '打印时间',
  ipaddress VARCHAR(50) DEFAULT NULL,
  workdate DATETIME DEFAULT NULL,
  shiftid INT(11) DEFAULT 0,
  authorizer VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX t_nodeclass_classNo (classNo)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_nodeclass_copy
--
DROP TABLE IF EXISTS t_nodeclass_copy;
CREATE TABLE t_nodeclass_copy (
  id INT(11) NOT NULL AUTO_INCREMENT,
  classNo VARCHAR(50) DEFAULT NULL COMMENT '结单编号',
  posID VARCHAR(50) DEFAULT NULL COMMENT 'POS id',
  operatorID VARCHAR(30) DEFAULT NULL COMMENT '操作员ID',
  operatorName VARCHAR(50) DEFAULT NULL COMMENT '操作员姓名',
  vIn DATETIME DEFAULT NULL COMMENT '签到时间',
  vOut DATETIME DEFAULT NULL COMMENT '签退时间',
  prettyCash DECIMAL(8, 2) DEFAULT 0.00 COMMENT '备用金',
  lastNonTable INT(11) DEFAULT NULL COMMENT '前班未结台数',
  lastNonDeposit DECIMAL(8, 2) DEFAULT 0.00 COMMENT '前班未结押金',
  tBeginPeople INT(11) DEFAULT NULL COMMENT '本班开单人数',
  tBeginTableTotal INT(11) DEFAULT NULL COMMENT '本班开台总数',
  tNonClosingTable INT(11) DEFAULT NULL COMMENT '本班未结台数',
  tNonClosingMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本班未结金额',
  tNonClosingDeposit DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本班未退押金',
  tClosingTable INT(11) DEFAULT NULL COMMENT '本班已结台数',
  tClosingPeople INT(11) DEFAULT NULL COMMENT '本班已结人数',
  tPresentedMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本班赠单金额',
  tRFoodMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本班退菜金额',
  itemMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '品项消费',
  serviceMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '服务费',
  roomMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '包房费',
  lowConsComp DECIMAL(8, 2) DEFAULT 0.00 COMMENT '最低消费补齐',
  preferenceMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '优惠金额',
  accountsReceivableSubtotal DECIMAL(8, 2) DEFAULT 0.00 COMMENT '应收小计',
  removeMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '抹零金额',
  ratedPreferenceMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '定额优惠金额',
  accountsReceivableTotal DECIMAL(8, 2) DEFAULT 0.00 COMMENT '应收合计',
  includedMoneyTotal DECIMAL(8, 2) DEFAULT 0.00 COMMENT '计入收入合计',
  noIncludedMoneyTotal DECIMAL(8, 2) DEFAULT 0.00 COMMENT '不计入收入合计',
  TotalMoney DECIMAL(8, 2) DEFAULT 0.00 COMMENT '合计',
  tableware DECIMAL(8, 2) DEFAULT 0.00 COMMENT '餐具',
  drinks DECIMAL(8, 2) DEFAULT 0.00 COMMENT '酒水',
  drinksSmokeNoodle DECIMAL(8, 2) DEFAULT 0.00 COMMENT '酒水烟汤面',
  todayTurnover DECIMAL(8, 2) DEFAULT 0.00 COMMENT '本日营业总额',
  priterTime DATETIME DEFAULT NULL COMMENT '打印时间',
  ipaddress VARCHAR(50) DEFAULT NULL,
  workdate DATETIME DEFAULT NULL,
  shiftid INT(11) DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE INDEX t_nodeclass_classNo (classNo)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_open_log
--
DROP TABLE IF EXISTS t_open_log;
CREATE TABLE t_open_log (
  id VARCHAR(10) NOT NULL,
  username VARCHAR(20) DEFAULT NULL,
  inserttime datetime DEFAULT NULL,
  opendate datetime DEFAULT NULL,
  ipaddress VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_operation_log
--
DROP TABLE IF EXISTS t_operation_log;
CREATE TABLE t_operation_log (
  id VARCHAR(50) NOT NULL COMMENT '主键',
  tableno VARCHAR(50) DEFAULT NULL COMMENT '桌号',
  operationType INT(4) DEFAULT NULL COMMENT '（1：下单;2 :退菜） ',
  sequence INT(11) DEFAULT NULL COMMENT ' 顺序',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_order
--
DROP TABLE IF EXISTS t_order;
CREATE TABLE t_order (
  orderid VARCHAR(50) NOT NULL,
  userid VARCHAR(50) DEFAULT NULL,
  begintime DATETIME DEFAULT NULL,
  endtime DATETIME DEFAULT NULL,
  orderstatus INT(11) NOT NULL COMMENT '0 ???e? 1 ???????? 2 ????????????????  3 ???????',
  custnum INT(11) DEFAULT NULL,
  tableids VARCHAR(1000) DEFAULT NULL,
  specialrequied VARCHAR(100) DEFAULT NULL,
  womanNum INT(11) DEFAULT NULL,
  childNum INT(11) DEFAULT NULL,
  mannum INT(11) DEFAULT NULL,
  currenttableid VARCHAR(200) DEFAULT NULL,
  fulldiscountrate DECIMAL(8, 2) UNSIGNED ZEROFILL DEFAULT 000000.00 COMMENT '全单折扣',
  dueamount DECIMAL(8, 2) UNSIGNED ZEROFILL DEFAULT 000000.00 COMMENT '应收金额',
  discountamount DECIMAL(8, 2) UNSIGNED ZEROFILL DEFAULT 000000.00 COMMENT '折扣金额',
  freeamount DECIMAL(8, 2) UNSIGNED ZEROFILL DEFAULT 000000.00 COMMENT '优惠金额',
  wipeamount DECIMAL(8, 2) UNSIGNED ZEROFILL DEFAULT 000000.00 COMMENT '抹零金额',
  payway INT(11) DEFAULT NULL,
  partnername VARCHAR(50) DEFAULT NULL,
  couponname VARCHAR(100) DEFAULT NULL,
  disuserid VARCHAR(50) DEFAULT NULL,
  relateorderid VARCHAR(50) DEFAULT NULL,
  printcount INT(11) DEFAULT 0,
  befprintcount INT(11) DEFAULT 0,
  workdate DATETIME DEFAULT NULL COMMENT '工作日期',
  shiftid INT(11) DEFAULT 0 COMMENT '班别编号 0早班 1晚班',
  closeshiftid INT(11) DEFAULT 0,
  memberno VARCHAR(50) DEFAULT NULL,
  ymamount DECIMAL(8, 2) DEFAULT 0.00 COMMENT '优免金额',
  gzamount DECIMAL(8, 2) DEFAULT 0.00 COMMENT '挂帐金额',
  ssamount DECIMAL(8, 2) DEFAULT 0.00 COMMENT '实收金额 现金，银行卡，会员卡，会员积分',
  ageperiod VARCHAR(255) DEFAULT NULL,
  meid VARCHAR(100) DEFAULT NULL COMMENT 'PAD 端编码',
  orderseq INT(11) DEFAULT NULL,
  branchid INT(11) DEFAULT NULL,
  ordertype INT(11) DEFAULT 0,
  gzcode VARCHAR(50) DEFAULT NULL,
  gzname VARCHAR(50) DEFAULT NULL,
  gztele VARCHAR(20) DEFAULT NULL,
  gzuser VARCHAR(20) DEFAULT NULL,
  invoice_id VARCHAR(50) DEFAULT NULL,
  gift_status CHAR(2) DEFAULT '0',
  isfree TINYINT(1) DEFAULT 0 COMMENT '是否餐具需要收费0不收费1收费',
  num_of_meals INT(2) DEFAULT 0 COMMENT '用餐人数 pad专用',
  PRIMARY KEY (orderid),
  INDEX IX_t_order_begintime (branchid, begintime)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 234
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_order_detail
--
DROP TABLE IF EXISTS `t_order_detail`;
CREATE TABLE `t_order_detail` (
  `orderid` varchar(50) DEFAULT NULL,
  `dishid` varchar(50) DEFAULT NULL,
  `dishstatus` varchar(50) DEFAULT NULL COMMENT '0 ??????? 1 ??? 2 ??? ',
  `begintime` datetime DEFAULT NULL,
  `endtime` datetime DEFAULT NULL,
  `sperequire` varchar(200) DEFAULT NULL,
  `dishnum` varchar(50) DEFAULT NULL,
  `userName` varchar(100) DEFAULT NULL,
  `orderprice` decimal(10,2) DEFAULT NULL,
  `discountrate` decimal(10,2) DEFAULT '0.00' COMMENT '折扣率',
  `discountamount` decimal(10,2) DEFAULT '0.00' COMMENT '折扣金额',
  `fishcode` varchar(50) DEFAULT NULL COMMENT '使用鱼券',
  `dishtype` int(11) DEFAULT '0' COMMENT '0 单品 1 火锅 2 套餐',
  `status` int(11) DEFAULT '0',
  `dishunit` varchar(100) DEFAULT NULL,
  `payamount` decimal(10,2) DEFAULT NULL,
  `predisamount` decimal(10,2) DEFAULT NULL,
  `couponid` varchar(50) DEFAULT NULL,
  `disuserid` varchar(50) DEFAULT NULL,
  `orignalprice` decimal(10,2) DEFAULT NULL COMMENT '原始价格',
  `pricetype` varchar(10) DEFAULT NULL,
  `orderseq` varchar(50) DEFAULT NULL,
  `orderdetailid` varchar(50) NOT NULL,
  `relatedishid` varchar(4000) DEFAULT NULL,
  `ordertype` int(3) DEFAULT NULL COMMENT '''下单类型 0 正常 1 赠送''',
  `parentkey` varchar(255) DEFAULT NULL COMMENT '父类主键',
  `superkey` varchar(255) DEFAULT NULL COMMENT '套餐的主键',
  `ismaster` int(255) DEFAULT NULL COMMENT '是否是master 默认是 0 不是 1是',
  `primarykey` varchar(255) DEFAULT NULL COMMENT '菜品主键',
  `islatecooke` int(2) DEFAULT '0' COMMENT '0 否 1 是',
  `isadddish` int(2) DEFAULT NULL COMMENT '0 否 1 是',
  `childdishtype` int(2) DEFAULT NULL COMMENT '0 单品 1 火锅 2 套餐',
  `ispot` int(2) DEFAULT '0' COMMENT '是否是锅底 0 否 1 是',
  `relateorderid` varchar(255) DEFAULT NULL,
  `discarduserid` varchar(255) DEFAULT NULL,
  `discardreason` varchar(255) DEFAULT NULL,
  `debitamount` decimal(20,2) DEFAULT NULL COMMENT '单个菜品加权实际收入',
  PRIMARY KEY (`orderdetailid`),
  UNIQUE KEY `primarykey` (`primarykey`),
  KEY `IX_t_order_detail_begintime` (`begintime`),
  KEY `t_order_detail_orderdetailid` (`orderdetailid`),
  KEY `t_order_detail_orderid` (`orderid`),
  KEY `idx_orderprice` (`orderprice`),
  KEY `idx_dishid` (`dishid`)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 729
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_order_detail_discard
--
DROP TABLE IF EXISTS t_order_detail_discard;
CREATE TABLE t_order_detail_discard (
  orderid VARCHAR(50) DEFAULT NULL,
  dishid VARCHAR(50) DEFAULT NULL,
  dishstatus VARCHAR(50) DEFAULT NULL COMMENT '0 ??????? 1 ??? 2 ??? ',
  begintime DATETIME DEFAULT NULL,
  endtime DATETIME DEFAULT NULL,
  sperequire VARCHAR(200) DEFAULT NULL,
  dishnum VARCHAR(50) DEFAULT NULL,
  userName VARCHAR(100) DEFAULT NULL,
  orderprice DECIMAL(10, 2) DEFAULT NULL,
  discountrate DECIMAL(10, 2) DEFAULT 0.00 COMMENT '折扣率',
  discountamount DECIMAL(10, 2) DEFAULT 0.00 COMMENT '折扣金额',
  fishcode VARCHAR(50) DEFAULT NULL COMMENT '使用鱼券',
  dishtype INT(11) DEFAULT 0 COMMENT '0 单品 1 火锅 2 套餐',
  status INT(11) DEFAULT 0,
  dishunit VARCHAR(100) DEFAULT NULL COMMENT '菜品单位',
  payamount DECIMAL(10, 2) DEFAULT NULL,
  predisamount DECIMAL(10, 2) DEFAULT NULL,
  couponid VARCHAR(50) DEFAULT NULL,
  disuserid VARCHAR(50) DEFAULT NULL,
  orignalprice DECIMAL(10, 2) DEFAULT NULL COMMENT '原始价格',
  pricetype VARCHAR(10) DEFAULT NULL,
  orderseq INT(11) DEFAULT NULL,
  orderdetailid VARCHAR(50) NOT NULL,
  relatedishid VARCHAR(4000) DEFAULT NULL,
  ordertype INT(3) DEFAULT NULL COMMENT '''下单类型 0 正常 1 赠送''',
  parentkey VARCHAR(255) DEFAULT NULL COMMENT '父类主键',
  superkey VARCHAR(255) DEFAULT NULL COMMENT '套餐的主键',
  ismaster INT(255) DEFAULT NULL COMMENT '是否是master 默认是 0 不是 1是',
  primarykey VARCHAR(255) DEFAULT NULL COMMENT '菜品主键',
  islatecooke INT(2) DEFAULT 0 COMMENT '0 否 1 是',
  isadddish INT(2) DEFAULT NULL COMMENT '0 否 1 是',
  childdishtype INT(2) DEFAULT NULL COMMENT '0 单品 1 火锅 2 套餐',
  ispot INT(2) DEFAULT 0 COMMENT '是否是锅底 0 否 1 是',
  relateorderid VARCHAR(255) DEFAULT NULL,
  discarduserid VARCHAR(255) DEFAULT NULL,
  discardreason VARCHAR(255) DEFAULT NULL,
  debitamount DECIMAL(20, 2) DEFAULT NULL COMMENT '单个菜品加权实际收入'
)
ENGINE = INNODB
AVG_ROW_LENGTH = 494
CHARACTER SET utf8
COLLATE utf8_general_ci;



--
-- Definition for table t_order_detail_history
--
DROP TABLE IF EXISTS t_order_detail_history;
CREATE TABLE t_order_detail_history (
  orderid varchar(50) DEFAULT NULL,
  dishid varchar(50) DEFAULT NULL,
  dishstatus varchar(50) DEFAULT NULL COMMENT '0 ??????? 1 ??? 2 ??? ',
  begintime datetime DEFAULT NULL,
  endtime datetime DEFAULT NULL,
  sperequire varchar(200) DEFAULT NULL,
  dishnum varchar(50) DEFAULT NULL,
  userName varchar(100) DEFAULT NULL,
  orderprice decimal(10,2) DEFAULT NULL,
  discountrate decimal(10,2) DEFAULT '0.00' COMMENT '折扣率',
  discountamount decimal(10,2) DEFAULT '0.00' COMMENT '折扣金额',
  fishcode varchar(50) DEFAULT NULL COMMENT '使用鱼券',
  dishtype int(11) DEFAULT '0' COMMENT '0 单品 1 火锅 2 套餐',
  status int(11) DEFAULT '0',
  dishunit varchar(100) DEFAULT NULL COMMENT '菜品单位',
  payamount decimal(10,2) DEFAULT NULL,
  predisamount decimal(10,2) DEFAULT NULL,
  couponid varchar(50) DEFAULT NULL,
  disuserid varchar(50) DEFAULT NULL,
  orignalprice decimal(10,2) DEFAULT NULL COMMENT '原始价格',
  pricetype varchar(10) DEFAULT NULL,
  orderseq int(11) DEFAULT NULL,
  orderdetailid varchar(50) NOT NULL,
  relatedishid varchar(4000) DEFAULT NULL,
  ordertype int(3) DEFAULT NULL COMMENT '''下单类型 0 正常 1 赠送''',
  parentkey varchar(255) DEFAULT NULL COMMENT '父类主键',
  superkey varchar(255) DEFAULT NULL COMMENT '套餐的主键',
  ismaster int(255) DEFAULT NULL COMMENT '是否是master 默认是 0 不是 1是',
  primarykey varchar(255) DEFAULT NULL COMMENT '菜品主键',
  islatecooke int(2) DEFAULT '0' COMMENT '0 否 1 是',
  isadddish int(2) DEFAULT NULL COMMENT '0 否 1 是',
  childdishtype int(2) DEFAULT NULL COMMENT '0 单品 1 火锅 2 套餐',
  ispot int(2) DEFAULT '0' COMMENT '是否是锅底 0 否 1 是',
  relateorderid varchar(255) DEFAULT NULL,
  discarduserid varchar(255) DEFAULT NULL,
  discardreason varchar(255) DEFAULT NULL,
  debitamount decimal(20,2) DEFAULT NULL COMMENT '单个菜品加权实际收入'
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_order_detail_temp
--
DROP TABLE IF EXISTS t_order_detail_temp;
CREATE TABLE t_order_detail_temp (
  orderid VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  dishid VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  dishstatus VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '0 ??????? 1 ??? 2 ??? ',
  begintime DATETIME DEFAULT NULL,
  endtime DATETIME DEFAULT NULL,
  sperequire VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  dishnum VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  userName VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  orderprice DECIMAL(10, 2) DEFAULT NULL,
  discountrate DECIMAL(10, 2) DEFAULT 0.00 COMMENT '折扣率',
  discountamount DECIMAL(10, 2) DEFAULT 0.00 COMMENT '折扣金额',
  fishcode VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '使用鱼券',
  dishtype INT(11) UNSIGNED ZEROFILL DEFAULT 00000000000 COMMENT '下单类型 0 正常 1 赠送',
  status INT(11) DEFAULT 0,
  dishunit VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '菜品单位',
  payamount DECIMAL(10, 2) DEFAULT NULL,
  predisamount DECIMAL(10, 2) DEFAULT NULL,
  couponid VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  disuserid VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  orignalprice DECIMAL(10, 2) DEFAULT NULL COMMENT '菜品正常价格',
  pricetype VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '价格类型，0 正常 1 折扣 2 特价 3 特价 4 赠送 5 优免',
  printtype VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  relatedishid VARCHAR(3000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  orderseq INT(10) DEFAULT NULL,
  ordertype INT(3) DEFAULT NULL COMMENT '0 单品 1 火锅 2 套餐',
  parentkey VARCHAR(255) DEFAULT NULL COMMENT '父类主键',
  superkey VARCHAR(255) DEFAULT NULL COMMENT '套餐的主键',
  ismaster INT(255) DEFAULT NULL COMMENT '是否是master 默认是 0 不是 1是',
  primarykey VARCHAR(255) DEFAULT NULL COMMENT '菜品主键',
  islatecooke INT(2) DEFAULT 0 COMMENT '0 否 1 是',
  isadddish INT(2) DEFAULT NULL COMMENT '0 否 1 是',
  childdishtype INT(2) DEFAULT NULL COMMENT '0 单品 1 火锅 2 套餐',
  ispot INT(2) DEFAULT 0 COMMENT '是否是锅底 0 否 1 是',
  id INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id),
  UNIQUE INDEX t_order_detail_temp_id (id),
  INDEX t_order_detail_temp_orderid (orderid)
)
ENGINE = INNODB
AUTO_INCREMENT = 2628
AVG_ROW_LENGTH = 744
CHARACTER SET utf8
COLLATE utf8_general_ci;



--
-- Definition for table t_order_history
--
DROP TABLE IF EXISTS t_order_history;
CREATE TABLE t_order_history (
  orderid varchar(50) NOT NULL,
  userid varchar(50) DEFAULT NULL,
  begintime datetime DEFAULT NULL,
  endtime datetime DEFAULT NULL,
  orderstatus int(11) NOT NULL COMMENT '0 ???e? 1 ???????? 2 ????????????????  3 ???????',
  custnum int(11) DEFAULT NULL,
  tableids varchar(1000) DEFAULT NULL,
  specialrequied varchar(100) DEFAULT NULL,
  womanNum int(11) DEFAULT NULL,
  childNum int(11) DEFAULT NULL,
  mannum int(11) DEFAULT NULL,
  currenttableid varchar(200) DEFAULT NULL,
  fulldiscountrate decimal(8,2) unsigned zerofill DEFAULT '000000.00' COMMENT '全单折扣',
  dueamount decimal(8,2) unsigned zerofill DEFAULT '000000.00' COMMENT '应收金额',
  discountamount decimal(8,2) unsigned zerofill DEFAULT '000000.00' COMMENT '折扣金额',
  freeamount decimal(8,2) unsigned zerofill DEFAULT '000000.00' COMMENT '优惠金额',
  wipeamount decimal(8,2) unsigned zerofill DEFAULT '000000.00' COMMENT '抹零金额',
  payway int(11) DEFAULT NULL,
  partnername varchar(50) DEFAULT NULL,
  couponname varchar(100) DEFAULT NULL,
  disuserid varchar(50) DEFAULT NULL,
  relateorderid varchar(50) DEFAULT NULL,
  printcount int(11) DEFAULT '0',
  befprintcount int(11) DEFAULT '0',
  workdate datetime DEFAULT NULL COMMENT '工作日期',
  shiftid int(11) DEFAULT '0' COMMENT '班别编号 0早班 1晚班',
  closeshiftid int(11) DEFAULT '0',
  memberno varchar(50) DEFAULT NULL,
  ymamount decimal(8,2) DEFAULT '0.00' COMMENT '优免金额',
  gzamount decimal(8,2) DEFAULT '0.00' COMMENT '挂帐金额',
  ssamount decimal(8,2) DEFAULT '0.00' COMMENT '实收金额 现金，银行卡，会员卡，会员积分',
  ageperiod varchar(255) DEFAULT NULL,
  meid varchar(100) DEFAULT NULL COMMENT 'PAD 端编码',
  orderseq int(11) DEFAULT NULL,
  branchid int(11) DEFAULT NULL,
  ordertype int(11) DEFAULT '0',
  gzcode varchar(50) DEFAULT NULL,
  gzname varchar(50) DEFAULT NULL,
  gztele varchar(20) DEFAULT NULL,
  gzuser varchar(20) DEFAULT NULL,
  invoice_id varchar(50) DEFAULT NULL,
  gift_status char(2) DEFAULT '0',
  isfree TINYINT(1) DEFAULT 0 COMMENT '是否餐具需要收费0不收费1收费',
  num_of_meals INT(2) DEFAULT 0 COMMENT '用餐人数 pad专用'
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_order_member
--
DROP TABLE IF EXISTS t_order_member;
CREATE TABLE t_order_member (
  id INT(11) NOT NULL AUTO_INCREMENT,
  orderid VARCHAR(50) DEFAULT NULL,
  userid VARCHAR(50) DEFAULT NULL,
  ordertime DATETIME DEFAULT NULL COMMENT '交易时间',
  operatetype INT(11) DEFAULT 0 COMMENT '交易类型',
  business VARCHAR(50) DEFAULT NULL COMMENT '商户号',
  terminal VARCHAR(50) DEFAULT NULL COMMENT '终端号',
  `serial` VARCHAR(50) DEFAULT NULL,
  batchno VARCHAR(50) DEFAULT NULL,
  businessname VARCHAR(50) DEFAULT NULL,
  score DECIMAL(8, 2) DEFAULT 0.00,
  coupons DECIMAL(8, 2) DEFAULT 0.00,
  stored DECIMAL(8, 2) DEFAULT NULL,
  scorebalance DECIMAL(8, 2) DEFAULT 0.00,
  couponsbalance DECIMAL(8, 2) DEFAULT 0.00,
  storedbalance DECIMAL(8, 2) DEFAULT 0.00,
  cardno VARCHAR(50) DEFAULT NULL,
  valid INT(11) DEFAULT 0,
  psexpansivity VARCHAR(50) DEFAULT '' COMMENT '膨胀系数',
  netvalue DECIMAL(8, 2) DEFAULT 0.00 COMMENT '净值',
  Inflated DECIMAL(8, 2) DEFAULT 0.00 COMMENT '虚增',
  remark VARCHAR(500) DEFAULT NULL COMMENT '附件字段，用来备份信息。2015年11月19日备份净值和虚增',
  PRIMARY KEY (id),
  INDEX t_order_member_orderid (orderid)
)
ENGINE = INNODB
AUTO_INCREMENT = 432
AVG_ROW_LENGTH = 270
CHARACTER SET utf8
COLLATE utf8_general_ci;



--
-- Definition for table t_order_preferential
--
DROP TABLE IF EXISTS t_order_preferential;
CREATE TABLE t_order_preferential (
  id INT(11) NOT NULL AUTO_INCREMENT,
  orderid VARCHAR(50) DEFAULT NULL,
  couponid VARCHAR(50) DEFAULT NULL,
  couponname VARCHAR(100) DEFAULT NULL,
  partnername VARCHAR(50) DEFAULT NULL,
  couponrate DECIMAL(10, 2) DEFAULT 0.00,
  freeamount DECIMAL(10, 2) DEFAULT NULL,
  debitamount DECIMAL(10, 2) DEFAULT NULL,
  num INT(11) DEFAULT NULL,
  amount DECIMAL(10, 2) DEFAULT NULL,
  type INT(11) DEFAULT NULL,
  memo VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX t_order_preferential_orderid (orderid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_order_rule
--
DROP TABLE IF EXISTS t_order_rule;
CREATE TABLE t_order_rule (
  id INT(11) NOT NULL AUTO_INCREMENT,
  orderid VARCHAR(50) DEFAULT NULL,
  yhname VARCHAR(50) DEFAULT NULL,
  partnername VARCHAR(100) DEFAULT NULL,
  couponrate DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  freeamount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  debitamount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  memo VARCHAR(50) DEFAULT NULL,
  couponsno VARCHAR(50) DEFAULT NULL,
  num INT(11) DEFAULT 0,
  ftype INT(11) DEFAULT 0,
  banktype VARCHAR(50) DEFAULT NULL,
  ruleid VARCHAR(50) DEFAULT NULL,
  couponid VARCHAR(50) DEFAULT NULL,
  amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (id),
  INDEX fk_t_order_rule_orderid (orderid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1378
AVG_ROW_LENGTH = 215
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_p_no_discount_dish
--
DROP TABLE IF EXISTS t_p_no_discount_dish;
CREATE TABLE t_p_no_discount_dish (
  id VARCHAR(32) NOT NULL,
  discount_ticket VARCHAR(32) NOT NULL COMMENT '折扣券id',
  dish VARCHAR(50) NOT NULL COMMENT '菜品id',
  dish_title VARCHAR(300) DEFAULT NULL COMMENT '菜品名',
  unit VARCHAR(100) DEFAULT NULL COMMENT '单位（大份/小份）',
  unitflag TINYINT(1) DEFAULT 1 COMMENT '是否多计量单位菜品。0有多计量   1没有多计量',
  itemtype VARCHAR(50) DEFAULT NULL COMMENT '菜品分类',
  itemdesc VARCHAR(200) DEFAULT NULL COMMENT '菜品分类名',
  item_select TINYINT(1) DEFAULT NULL COMMENT '是否选择全类',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '不参与折扣菜品';

--
-- Definition for table t_p_preferential_activity
--
DROP TABLE IF EXISTS t_p_preferential_activity;
CREATE TABLE t_p_preferential_activity (
  id VARCHAR(32) NOT NULL,
  code CHAR(6) NOT NULL COMMENT '优惠活动编码',
  name VARCHAR(128) DEFAULT NULL COMMENT '优惠活动名称',
  name_first_letter VARCHAR(32) DEFAULT NULL COMMENT '优惠名称首字母',
  type CHAR(4) DEFAULT NULL COMMENT '优惠活动分类字典表主键',
  type_name VARCHAR(32) DEFAULT NULL COMMENT '优惠活动分类名',
  subtable_name VARCHAR(50) DEFAULT NULL,
  sub_type CHAR(4) DEFAULT NULL,
  sub_type_name VARCHAR(32) DEFAULT NULL,
  color CHAR(8) DEFAULT NULL COMMENT '优惠券rgb颜色',
  starttime DATETIME DEFAULT NULL COMMENT '有效期开始时间',
  endtime DATETIME DEFAULT NULL COMMENT '有效期结束时间',
  apply_all TINYINT(1) DEFAULT NULL COMMENT '是否适用所有门店',
  activity_introduction VARCHAR(1024) DEFAULT NULL COMMENT '活动介绍',
  use_notice VARCHAR(1024) DEFAULT NULL COMMENT '使用须知',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  creator VARCHAR(50) DEFAULT NULL COMMENT '创建者',
  status VARCHAR(5) DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE INDEX code (code)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 378
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '优惠活动主表';

--
-- Definition for table t_p_preferential_branch
--
DROP TABLE IF EXISTS t_p_preferential_branch;
CREATE TABLE t_p_preferential_branch (
  preferential VARCHAR(32) NOT NULL COMMENT '优惠活动id',
  branch INT(11) NOT NULL COMMENT '门店id',
  branch_name VARCHAR(255) DEFAULT NULL COMMENT '门店名',
  PRIMARY KEY (preferential, branch)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 160
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '优惠活动指定门店';

--
-- Definition for table t_p_preferential_detail
--
DROP TABLE IF EXISTS t_p_preferential_detail;
CREATE TABLE t_p_preferential_detail (
  id VARCHAR(40) NOT NULL,
  preferential VARCHAR(32) DEFAULT NULL COMMENT '优惠券主键',
  dish VARCHAR(50) DEFAULT NULL COMMENT '特价菜品id',
  dish_title VARCHAR(300) DEFAULT NULL COMMENT '特价菜品名称',
  price DECIMAL(10, 4) DEFAULT NULL COMMENT '特价菜品价格',
  sequence INT(11) DEFAULT NULL COMMENT '序号',
  unit VARCHAR(100) DEFAULT NULL COMMENT '特价菜品计量单位',
  unitflag TINYINT(1) DEFAULT 1 COMMENT '是否多计量单位菜品。0有多计量   1没有多计量',
  discount DECIMAL(6, 4) DEFAULT NULL COMMENT '折扣（折扣券和内部优免）',
  amount DECIMAL(10, 4) DEFAULT NULL COMMENT '券面金额（代金券）、抵用金额（团购券）',
  bill_amount DECIMAL(10, 4) DEFAULT NULL COMMENT '团购券销售金额',
  free_reason VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '手工优免原因',
  company_name VARCHAR(200) DEFAULT NULL COMMENT '内部优免单位名称',
  company_first_letter VARCHAR(100) DEFAULT NULL COMMENT '内部优免单位名称首字母',
  can_credit TINYINT(1) DEFAULT NULL COMMENT '内部优免是否可挂账',
  starttime DATETIME DEFAULT NULL COMMENT '内部优免有效期开始时间',
  endtime DATETIME DEFAULT NULL COMMENT '内部优免有效期结束时间',
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 224
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '优惠子表（不同分类优惠活动合并成一张子表）';

--
-- Definition for table t_p_preferential_type_dict
--
DROP TABLE IF EXISTS t_p_preferential_type_dict;
CREATE TABLE t_p_preferential_type_dict (
  code CHAR(4) NOT NULL COMMENT '分类编码',
  name VARCHAR(32) NOT NULL COMMENT '分类名',
  subtable_name VARCHAR(50) DEFAULT NULL COMMENT '优惠券子表名',
  is_subtype TINYINT(1) DEFAULT NULL,
  parent_type CHAR(4) DEFAULT NULL,
  PRIMARY KEY (code),
  UNIQUE INDEX name (name)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '优惠分类字典表';





--
-- Definition for table t_pictures
--
DROP TABLE IF EXISTS t_pictures;
CREATE TABLE t_pictures (
  picid VARCHAR(50) NOT NULL,
  picname VARCHAR(50) DEFAULT NULL,
  orderNo VARCHAR(50) DEFAULT NULL,
  status INT(10) DEFAULT NULL,
  picpath VARCHAR(50) DEFAULT NULL,
  detail MEDIUMTEXT DEFAULT NULL,
  PRIMARY KEY (picid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_preferential_report
--
DROP TABLE IF EXISTS t_preferential_report;
CREATE TABLE t_preferential_report (
  preferid INT(11) NOT NULL AUTO_INCREMENT,
  orderid VARCHAR(50) DEFAULT NULL,
  activity_type VARCHAR(100) DEFAULT NULL,
  activity_name VARCHAR(200) DEFAULT NULL,
  date_type VARCHAR(2) DEFAULT NULL,
  pay_type VARCHAR(20) DEFAULT NULL,
  pay_way INT(11) DEFAULT NULL,
  num INT(11) DEFAULT NULL,
  amount DECIMAL(10, 2) DEFAULT NULL,
  should_amount DECIMAL(10, 2) DEFAULT NULL,
  paidin_amount DECIMAL(10, 2) DEFAULT NULL,
  statistic_time DATE DEFAULT NULL,
  created_date DATETIME DEFAULT NULL,
  PRIMARY KEY (preferid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_printcenter
--
DROP TABLE IF EXISTS t_printcenter;
CREATE TABLE t_printcenter (
  id VARCHAR(50) NOT NULL,
  orderid VARCHAR(50) NOT NULL,
  printcount INT(11) DEFAULT NULL,
  userid VARCHAR(50) DEFAULT NULL,
  printtype INT(11) DEFAULT NULL,
  printstatus INT(11) DEFAULT NULL,
  printcontent VARCHAR(50) DEFAULT NULL,
  printtime DATETIME DEFAULT NULL,
  printipdress VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UQ_t_printcenter_id (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_printdish
--
DROP TABLE IF EXISTS t_printdish;
CREATE TABLE t_printdish (
  printdishid VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  printobjid VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  dishname VARCHAR(300) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '菜品名称',
  dishnum VARCHAR(10) DEFAULT NULL,
  dishprice DECIMAL(10, 2) DEFAULT NULL,
  totalamount DECIMAL(10, 2) DEFAULT NULL,
  payamount DECIMAL(10, 2) DEFAULT NULL,
  sperequire VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  tableNomsg VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  maxDishCount INT(11) DEFAULT NULL,
  dishUnit VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '菜品单位',
  printipaddress VARCHAR(100) DEFAULT NULL,
  printport VARCHAR(10) DEFAULT NULL,
  printnum INT(5) DEFAULT NULL,
  dishid VARCHAR(50) DEFAULT NULL,
  printtype VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  orderseq INT(11) DEFAULT NULL,
  relatedishid VARCHAR(5000) DEFAULT NULL,
  dishtype INT(11) DEFAULT NULL COMMENT '0  1 2',
  printerId VARBINARY(255) DEFAULT NULL,
  ordertype INT(3) DEFAULT NULL COMMENT '0 单品 1 火锅 2 套餐',
  parentkey VARCHAR(255) DEFAULT NULL COMMENT '父类主键',
  superkey VARCHAR(255) DEFAULT NULL COMMENT '套餐的主键',
  ismaster INT(255) DEFAULT NULL COMMENT '是否是master 默认是 0 不是 1是',
  primarykey VARCHAR(255) DEFAULT NULL COMMENT '菜品主键',
  islatecooke INT(2) DEFAULT 0 COMMENT '0 否 1 是',
  isadddish INT(2) DEFAULT NULL COMMENT '0 否 1 是',
  childdishtype INT(2) DEFAULT NULL COMMENT '0 单品 1 火锅 2 套餐',
  ispot INT(2) DEFAULT 0 COMMENT '是否是 锅底 0 否 1 是',
  PRIMARY KEY (printdishid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_printer
--
DROP TABLE IF EXISTS t_printer;
CREATE TABLE t_printer (
  printerid VARCHAR(50) NOT NULL,
  printerNo VARCHAR(50) DEFAULT NULL,
  printername VARCHAR(50) DEFAULT NULL,
  printertype INT(11) DEFAULT NULL,
  createuserid VARCHAR(50) DEFAULT NULL,
  inserttime VARCHAR(50) DEFAULT NULL,
  ipaddress VARCHAR(50) DEFAULT NULL,
  port VARCHAR(50) DEFAULT NULL,
  status INT(11) DEFAULT NULL,
  printnum INT(11) DEFAULT NULL,
  PRIMARY KEY (printerid),
  UNIQUE INDEX UQ_t_printer_printerid (printerid)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_printer_area
--
DROP TABLE IF EXISTS t_printer_area;
CREATE TABLE t_printer_area (
  id VARCHAR(50) DEFAULT NULL,
  areaid VARCHAR(50) DEFAULT NULL COMMENT '区域id',
  printerid VARCHAR(50) DEFAULT NULL COMMENT '打印机id',
  inserttime DATETIME DEFAULT NULL COMMENT '插入时间',
  tableid VARCHAR(50) DEFAULT NULL,
  status INT(2) DEFAULT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 330
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_printer_detail
--
DROP TABLE IF EXISTS t_printer_detail;
CREATE TABLE t_printer_detail (
  id VARCHAR(50) NOT NULL,
  printerid VARCHAR(50) DEFAULT NULL,
  dishid VARCHAR(50) DEFAULT NULL,
  status INT(2) DEFAULT NULL COMMENT '0 有效 1 无效',
  columnid VARCHAR(50) DEFAULT NULL COMMENT '菜品分类id',
  groupsequence varchar(20) DEFAULT NULL COMMENT '组合的序号',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 285
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_printobj
--
DROP TABLE IF EXISTS t_printobj;
CREATE TABLE t_printobj (
  id VARCHAR(50) NOT NULL,
  printtype INT(11) DEFAULT NULL,
  messagemsg VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  orderno VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  username VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  tableno VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  timemsg VARCHAR(50) DEFAULT NULL,
  customerprinterip VARCHAR(100) DEFAULT NULL,
  customerprinterport VARCHAR(10) DEFAULT NULL,
  tableArea VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  tableid VARCHAR(255) DEFAULT NULL,
  orderseq INT(11) DEFAULT NULL,
  custnum VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_resource
--
DROP TABLE IF EXISTS t_resource;
CREATE TABLE t_resource (
  resourcesId VARCHAR(50) NOT NULL,
  resourcesPid VARCHAR(50) DEFAULT NULL,
  resourcesName VARCHAR(100) NOT NULL,
  resourcesPath VARCHAR(200) NOT NULL,
  resourcesDesc VARCHAR(200) DEFAULT NULL,
  resourcesType VARCHAR(50) DEFAULT NULL COMMENT '1：菜单 2：资源 3：按钮',
  indexValue VARCHAR(50) DEFAULT NULL,
  status INT(11) NOT NULL,
  createTime DATETIME DEFAULT NULL,
  PRIMARY KEY (resourcesId),
  UNIQUE INDEX UQ_t_resource_resourcesId (resourcesId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_resource_role
--
DROP TABLE IF EXISTS t_resource_role;
CREATE TABLE t_resource_role (
  resourceId VARCHAR(50) NOT NULL,
  roleid VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (resourceId, roleid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;



--
-- Definition for table t_settlement
--
DROP TABLE IF EXISTS t_settlement;
CREATE TABLE t_settlement (
  settledId VARCHAR(50) NOT NULL,
  debitamount DECIMAL(10, 2) DEFAULT NULL,
  creditamount DECIMAL(10, 2) DEFAULT NULL,
  orderid VARCHAR(50) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL,
  indiscount DECIMAL(10, 2) DEFAULT NULL,
  outdiscount DECIMAL(10, 2) DEFAULT NULL,
  userid VARCHAR(50) NOT NULL,
  settleddetailid VARCHAR(50) DEFAULT NULL,
  cashamount DECIMAL(10, 2) DEFAULT NULL,
  bankamount DECIMAL(10, 2) DEFAULT NULL,
  memeberamount DECIMAL(10, 2) DEFAULT NULL,
  status INT(11) DEFAULT NULL COMMENT '是否结算：1结算 0反结算',
  couponamount DECIMAL(10, 2) DEFAULT NULL,
  feeamount DECIMAL(10, 2) DEFAULT NULL,
  incometype INT(11) DEFAULT NULL,
  opendate DATE DEFAULT NULL,
  shiftid INT(11) DEFAULT 0 COMMENT '结算时的班别 0早市 1晚市',
  isclear INT(11) DEFAULT 0 COMMENT '1表示已经清过机',
  PRIMARY KEY (settledId),
  INDEX t_order_settlement_orderid (orderid),
  UNIQUE INDEX UQ_t_settlement_settledId (settledId)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 218
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_settlement_detail
--
DROP TABLE IF EXISTS t_settlement_detail;
CREATE TABLE t_settlement_detail (
  sdetailid VARCHAR(50) NOT NULL,
  orderid VARCHAR(50) NOT NULL,
  dishid VARCHAR(50) DEFAULT NULL,
  normalprice DECIMAL(10, 2) DEFAULT NULL,
  discountamount DECIMAL(10, 2) DEFAULT NULL,
  discountid VARCHAR(50) DEFAULT NULL COMMENT '¹ØÁªt_discount ±í',
  couponid VARCHAR(50) DEFAULT NULL COMMENT '¹ØÁªt_coupons',
  couponamount DECIMAL(10, 2) DEFAULT NULL,
  payamount DECIMAL(10, 2) DEFAULT NULL COMMENT '实际支付金额',
  couponNum INT(11) DEFAULT NULL,
  feeamount DECIMAL(10, 2) DEFAULT NULL,
  settledid VARCHAR(50) DEFAULT NULL,
  incometype INT(11) DEFAULT NULL COMMENT '是否内部收入',
  membercardno VARCHAR(50) DEFAULT NULL,
  bankcardno VARCHAR(50) DEFAULT NULL,
  opendate DATE DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  payway INT(11) DEFAULT NULL COMMENT '结算方式：见字典表payway',
  isclear SMALLINT(8) UNSIGNED ZEROFILL DEFAULT 00000000,
  debitParterner VARCHAR(10) DEFAULT NULL COMMENT '挂账单位',
  inserttime DATETIME DEFAULT NULL,
  coupondetailid VARCHAR(50) DEFAULT NULL COMMENT '优惠明细主键',
  PRIMARY KEY (sdetailid),
  INDEX t_order_settlement_detail_orderid (orderid),
  UNIQUE INDEX UQ_t_settlement_detail_sdetailid (sdetailid)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 336
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_settlement_detail_history
--
DROP TABLE IF EXISTS t_settlement_detail_history;
CREATE TABLE t_settlement_detail_history (
  sdetailid VARCHAR(50) NOT NULL,
  orderid VARCHAR(50) NOT NULL,
  dishid VARCHAR(50) DEFAULT NULL,
  normalprice DECIMAL(10, 2) DEFAULT NULL,
  discountamount DECIMAL(10, 2) DEFAULT NULL,
  discountid VARCHAR(50) DEFAULT NULL COMMENT '¹ØÁªt_discount ±í',
  couponid VARCHAR(50) DEFAULT NULL COMMENT '¹ØÁªt_coupons',
  couponamount DECIMAL(10, 2) DEFAULT NULL,
  payamount DECIMAL(10, 2) DEFAULT NULL COMMENT '实际支付金额',
  couponNum INT(11) DEFAULT NULL,
  feeamount DECIMAL(10, 2) DEFAULT NULL,
  settledid VARCHAR(50) DEFAULT NULL,
  incometype INT(11) DEFAULT NULL COMMENT '是否内部收入',
  membercardno VARCHAR(50) DEFAULT NULL,
  bankcardno VARCHAR(50) DEFAULT NULL,
  opendate DATE DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  payway INT(11) DEFAULT NULL COMMENT '结算方式：见字典表payway',
  isclear SMALLINT(8) UNSIGNED ZEROFILL DEFAULT 00000000,
  debitParterner VARCHAR(10) DEFAULT NULL COMMENT '挂账单位',
  inserttime DATETIME DEFAULT NULL,
  coupondetailid VARCHAR(50) DEFAULT NULL COMMENT '优惠明细主键',
  id VARCHAR(50) DEFAULT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 331
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_settlement_history
--
DROP TABLE IF EXISTS t_settlement_history;
CREATE TABLE t_settlement_history (
  settledId VARCHAR(50) NOT NULL,
  debitamount DECIMAL(10, 2) DEFAULT NULL,
  creditamount DECIMAL(10, 2) DEFAULT NULL,
  orderid VARCHAR(50) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL,
  indiscount DECIMAL(10, 2) DEFAULT NULL,
  outdiscount DECIMAL(10, 2) DEFAULT NULL,
  userid VARCHAR(50) NOT NULL,
  settleddetailid VARCHAR(50) DEFAULT NULL,
  cashamount DECIMAL(10, 2) DEFAULT NULL,
  bankamount DECIMAL(10, 2) DEFAULT NULL,
  memeberamount DECIMAL(10, 2) DEFAULT NULL,
  status INT(11) DEFAULT NULL COMMENT '是否结算：1结算 0反结算',
  couponamount DECIMAL(10, 2) DEFAULT NULL,
  feeamount DECIMAL(10, 2) DEFAULT NULL,
  incometype INT(11) DEFAULT NULL,
  opendate DATE DEFAULT NULL,
  shiftid INT(11) DEFAULT 0 COMMENT '结算时的班别 0早市 1晚市',
  isclear INT(11) DEFAULT 0 COMMENT '1表示已经清过机',
  id VARCHAR(50) DEFAULT NULL,
  reason VARCHAR(100) DEFAULT NULL,
  rebacktime DATETIME DEFAULT NULL,
  again_settle_nums int(3) DEFAULT 1,
  authorizer_name VARCHAR(50),
  Inflated decimal(8,2)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 496
CHARACTER SET utf8
COLLATE utf8_general_ci;



--
-- Definition for table t_settlement_report
--
DROP TABLE IF EXISTS t_settlement_report;
CREATE TABLE t_settlement_report (
  settlement_id INT(11) NOT NULL AUTO_INCREMENT,
  date_type VARCHAR(2) DEFAULT NULL,
  pay_type VARCHAR(20) DEFAULT NULL,
  pay_way INT(11) DEFAULT NULL,
  num INT(11) DEFAULT NULL,
  amount DECIMAL(10, 2) DEFAULT NULL,
  statistic_time DATE DEFAULT NULL,
  created_date DATETIME DEFAULT NULL,
  PRIMARY KEY (settlement_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_syn_record
--
DROP TABLE IF EXISTS t_syn_record;
CREATE TABLE t_syn_record (
  id INT(11) NOT NULL AUTO_INCREMENT,
  branchid VARCHAR(30) DEFAULT NULL COMMENT '同步的分店id',
  syntime DATETIME DEFAULT NULL COMMENT '同步时间',
  status INT(2) DEFAULT NULL COMMENT '状态 0 成功 1 失败',
  datapath VARCHAR(100) DEFAULT NULL COMMENT '数据同步的地址',
  endtime DATETIME DEFAULT NULL COMMENT '同步结束时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4348
AVG_ROW_LENGTH = 71
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_syn_record_history
--
DROP TABLE IF EXISTS t_syn_record_history;
CREATE TABLE t_syn_record_history (
  id INT(11) NOT NULL DEFAULT 0,
  branchid VARCHAR(30) DEFAULT NULL COMMENT '同步的分店id',
  syntime DATETIME DEFAULT NULL COMMENT '同步时间',
  status INT(2) DEFAULT NULL COMMENT '状态 0 成功 1 失败',
  datapath VARCHAR(100) DEFAULT NULL COMMENT '数据同步的地址',
  endtime DATETIME DEFAULT NULL COMMENT '同步结束时间'
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_syn_sql
--
DROP TABLE IF EXISTS t_syn_sql;
CREATE TABLE t_syn_sql (
  id VARBINARY(50) NOT NULL,
  branchid VARCHAR(50) DEFAULT NULL COMMENT '分店id',
  sqltext LONGTEXT DEFAULT NULL COMMENT 'sql 语句',
  inserttime TIMESTAMP NULL DEFAULT NULL COMMENT '生成日期',
  status INT(11) DEFAULT NULL COMMENT '状态 默认是0 ，同步完是1',
  generattime TIMESTAMP NULL DEFAULT NULL COMMENT '生成日期',
  orderseqno INT(11) DEFAULT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1458
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_syn_sql_history
--
DROP TABLE IF EXISTS t_syn_sql_history;
CREATE TABLE t_syn_sql_history (
  id VARBINARY(50) NOT NULL,
  branchid VARCHAR(50) DEFAULT NULL COMMENT '分店id',
  sqltext LONGTEXT DEFAULT NULL COMMENT 'sql 语句',
  inserttime TIMESTAMP NULL DEFAULT NULL COMMENT '生成日期',
  status INT(11) DEFAULT NULL COMMENT '状态 默认是0 ，同步完是1',
  generattime TIMESTAMP NULL DEFAULT NULL COMMENT '生成日期',
  orderseqno INT(11) DEFAULT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1486
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_syn_sql_temp
--
DROP TABLE IF EXISTS t_syn_sql_temp;
CREATE TABLE t_syn_sql_temp (
  id VARBINARY(50) NOT NULL,
  branchid VARCHAR(50) DEFAULT NULL COMMENT '分店id',
  sqltext LONGTEXT DEFAULT NULL COMMENT 'sql 语句',
  inserttime TIMESTAMP NULL DEFAULT NULL COMMENT '生成日期',
  status INT(11) DEFAULT NULL COMMENT '状态 默认是0 ，同步完是1',
  generattime TIMESTAMP NULL DEFAULT NULL COMMENT '生成日期',
  orderseqno INT(11) DEFAULT NULL
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_syncclient
--
DROP TABLE IF EXISTS t_syncclient;
CREATE TABLE t_syncclient (
  id INT(11) NOT NULL AUTO_INCREMENT,
  client VARCHAR(100) DEFAULT NULL,
  msgid INT(11) DEFAULT NULL,
  receivetime DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX t_syncclient_fk2 (client),
  INDEX t_syncclient_fk3 (receivetime)
)
ENGINE = INNODB
AUTO_INCREMENT = 2255
AVG_ROW_LENGTH = 139
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_syncmsg
--
DROP TABLE IF EXISTS t_syncmsg;
CREATE TABLE t_syncmsg (
  id INT(11) NOT NULL AUTO_INCREMENT,
  msgtype INT(11) DEFAULT 0,
  msg VARCHAR(255) DEFAULT NULL,
  msgtime DATETIME DEFAULT NULL,
  sendnum INT(11) DEFAULT 0,
  receive INT(11) DEFAULT NULL,
  needretry INT(11) DEFAULT 0,
  PRIMARY KEY (id),
  INDEX t_syncmsg (msgtime)
)
ENGINE = INNODB
AUTO_INCREMENT = 2109
AVG_ROW_LENGTH = 93
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_table
--
DROP TABLE IF EXISTS t_table;
CREATE TABLE t_table (
  tableid VARCHAR(50) NOT NULL,
  position VARCHAR(50) DEFAULT NULL,
  status INT(11) DEFAULT NULL,
  restaurantId VARCHAR(20) DEFAULT NULL,
  isVip INT(11) DEFAULT NULL,
  iscompartment INT(11) DEFAULT NULL,
  isavailable VARCHAR(20) DEFAULT NULL,
  buildingNo VARCHAR(50) DEFAULT NULL,
  minprice DECIMAL(10, 2) DEFAULT NULL,
  fixprice DECIMAL(10, 2) DEFAULT NULL,
  tableNo VARCHAR(50) DEFAULT NULL,
  personNum INT(11) DEFAULT NULL,
  tabletype VARCHAR(5) DEFAULT NULL,
  areaid VARCHAR(50) NOT NULL,
  tableName VARCHAR(50) DEFAULT NULL,
  orderid VARCHAR(50) DEFAULT NULL,
  custPrinter VARCHAR(50) DEFAULT NULL COMMENT '客用单打印机',
  modifytime DATETIME DEFAULT NULL,
  PRIMARY KEY (tableid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_tablearea
--
DROP TABLE IF EXISTS t_tablearea;
CREATE TABLE t_tablearea (
  areaid VARCHAR(50) NOT NULL,
  areaNo INT(10) DEFAULT NULL,
  areaname VARCHAR(10) DEFAULT NULL,
  status INT(10) DEFAULT NULL,
  custPrinter VARCHAR(50) DEFAULT NULL COMMENT '客用单打印机',
  areaSort INT(11) DEFAULT NULL,
  modifytime DATETIME DEFAULT NULL,
  branchid VARCHAR(50) DEFAULT NULL COMMENT '分店编码',
  PRIMARY KEY (areaid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_teller_cash
--
DROP TABLE IF EXISTS t_teller_cash;
CREATE TABLE t_teller_cash (
  id INT(50) NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) DEFAULT NULL,
  opendate DATE DEFAULT NULL,
  insertdate DATETIME DEFAULT NULL,
  ipaddress VARCHAR(50) DEFAULT NULL,
  cashamount DECIMAL(10, 2) DEFAULT NULL,
  status INT(11) DEFAULT NULL,
  shiftid INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 53
AVG_ROW_LENGTH = 356
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_template
--
DROP TABLE IF EXISTS t_template;
CREATE TABLE t_template (
  id VARCHAR(50) NOT NULL,
  templateid VARCHAR(50) DEFAULT NULL,
  createuserid VARCHAR(50) DEFAULT NULL COMMENT '创建者id',
  name VARCHAR(50) DEFAULT NULL COMMENT '模板名称',
  type VARCHAR(100) DEFAULT NULL COMMENT '模板类型',
  `data` MEDIUMTEXT DEFAULT NULL,
  status INT(11) DEFAULT NULL,
  releaseTime DATETIME DEFAULT NULL,
  createTime DATETIME DEFAULT NULL COMMENT '创建时间',
  articleids MEDIUMTEXT DEFAULT NULL,
  sort INT(10) DEFAULT NULL COMMENT '排序',
  columnid VARCHAR(50) DEFAULT NULL COMMENT '分类id',
  menuid VARCHAR(50) DEFAULT NULL COMMENT '菜谱id',
  columnsort INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UQ_t_template_id (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 279
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_template_detail
--
DROP TABLE IF EXISTS t_template_detail;
CREATE TABLE t_template_detail (
  id VARCHAR(50) NOT NULL DEFAULT '' COMMENT '主键',
  templateid VARCHAR(50) DEFAULT NULL COMMENT '模板id',
  menuid VARCHAR(50) DEFAULT NULL COMMENT '菜谱id',
  location VARCHAR(10) DEFAULT NULL COMMENT 'A模板第几个',
  sortnum INT(11) DEFAULT NULL COMMENT '排序',
  redishid VARCHAR(50) DEFAULT NULL COMMENT '菜品id',
  image VARCHAR(200) DEFAULT NULL COMMENT '图片路径',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 663
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_template_dishunit
--
DROP TABLE IF EXISTS t_template_dishunit;
CREATE TABLE t_template_dishunit (
  id VARCHAR(50) NOT NULL,
  dishid VARCHAR(50) DEFAULT NULL COMMENT '菜品id',
  menuid VARCHAR(50) DEFAULT NULL COMMENT '菜谱ID',
  dishname varchar(300) DEFAULT NULL COMMENT '菜品名称',
  dishintroduction varchar(800) DEFAULT NULL COMMENT '菜品介绍',
  unit varchar(100) DEFAULT NULL COMMENT '菜品单位',
  price DECIMAL(10, 2) DEFAULT NULL COMMENT '价格',
  vipprice DECIMAL(10, 2) DEFAULT NULL COMMENT '会员价',
  status INT(4) DEFAULT 0 COMMENT '状态，估清状态（1估清0非估清）',
  recommend INT(4) DEFAULT NULL,
  sort INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX ix_t_template_dishunit_dishid (dishid)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 564
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_user
--
DROP TABLE IF EXISTS t_user;
CREATE TABLE t_user (
  userId VARCHAR(50) NOT NULL,
  userName VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  fullName VARCHAR(50) NOT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  userType VARCHAR(50) NOT NULL,
  createTime DATETIME NOT NULL,
  status INT(2) NOT NULL COMMENT '0 失效  1 有效  2 注销',
  lastlogintime DATETIME DEFAULT NULL COMMENT '最近一次登录时间',
  PRIMARY KEY (userId),
  UNIQUE INDEX UQ_t_user_userId (userId),
  UNIQUE INDEX UQ_t_user_userName (userName)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_user_complaint
--
DROP TABLE IF EXISTS t_user_complaint;
CREATE TABLE t_user_complaint (
  id VARCHAR(50) NOT NULL DEFAULT '',
  orderid VARCHAR(50) DEFAULT NULL,
  device_type CHAR(1) DEFAULT NULL,
  device_no VARCHAR(30) DEFAULT NULL,
  userid VARCHAR(50) DEFAULT NULL,
  complaint_start_time DATETIME DEFAULT NULL,
  complaint_opinion VARCHAR(50) DEFAULT NULL,
  photo_url VARCHAR(100) DEFAULT NULL,
  visit_date DATETIME DEFAULT NULL,
  visiter VARCHAR(20) DEFAULT NULL,
  visit_record VARCHAR(100) DEFAULT NULL,
  problem_solver VARCHAR(20) DEFAULT NULL,
  result VARCHAR(100) DEFAULT NULL,
  guest_opinion CHAR(1) DEFAULT NULL,
  message_id VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 712
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_user_instrument
--
DROP TABLE IF EXISTS t_user_instrument;
CREATE TABLE t_user_instrument (
  id VARCHAR(50) NOT NULL,
  userid VARCHAR(50) DEFAULT NULL,
  instrumentid VARCHAR(50) DEFAULT NULL,
  inserttime DATETIME DEFAULT NULL,
  logintime DATETIME DEFAULT NULL,
  logouttime DATETIME DEFAULT NULL,
  status INT(11) DEFAULT NULL COMMENT '当前 手环状态 0 正常 1 失效',
  tableno VARCHAR(50) DEFAULT NULL COMMENT '桌号',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 119
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_user_role
--
DROP TABLE IF EXISTS t_user_role;
CREATE TABLE t_user_role (
  roleId VARCHAR(50) NOT NULL,
  userid VARCHAR(50) NOT NULL,
  PRIMARY KEY (roleId, userid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_version
--
DROP TABLE IF EXISTS t_version;
CREATE TABLE t_version (
  versionNo VARCHAR(50) NOT NULL,
  releaseNote VARCHAR(50) DEFAULT NULL,
  updateUrl VARCHAR(200) NOT NULL,
  updatetype INT(11) NOT NULL DEFAULT 0 COMMENT '1： android平板  2：android手机 3 POS',
  isinforce INT(11) DEFAULT NULL COMMENT '0 是 1 否',
  PRIMARY KEY (updatetype),
  UNIQUE INDEX UQ_t_version_versionNo (versionNo)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table tableseqno
--
DROP TABLE IF EXISTS tableseqno;
CREATE TABLE tableseqno (
  name VARCHAR(20) NOT NULL,
  val INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (name)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 20
CHARACTER SET utf8
COLLATE utf8_general_ci;


--
-- Definition for table t_nodeclass_detail
--
DROP TABLE IF EXISTS t_nodeclass_detail;
CREATE TABLE t_nodeclass_detail (
  id INT(11) NOT NULL AUTO_INCREMENT,
  sdetailid VARCHAR(50) DEFAULT NULL,
  classNo VARCHAR(50) NOT NULL,
  orderid VARCHAR(50) NOT NULL,
  dishid VARCHAR(50) DEFAULT NULL,
  normalprice DECIMAL(10, 2) DEFAULT 0.00,
  discountamount DECIMAL(10, 2) DEFAULT 0.00,
  discountid VARCHAR(50) DEFAULT NULL,
  couponid VARCHAR(50) DEFAULT NULL,
  couponamount DECIMAL(10, 2) DEFAULT 0.00,
  payamount DECIMAL(10, 2) DEFAULT 0.00,
  couponNum INT(11) DEFAULT 0,
  feeamount DECIMAL(10, 2) DEFAULT 0.00,
  settledid VARCHAR(50) DEFAULT NULL,
  incometype INT(11) DEFAULT NULL,
  membercardno VARCHAR(50) DEFAULT NULL,
  bankcardno VARCHAR(50) DEFAULT NULL,
  opendate DATE DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  payway INT(11) DEFAULT NULL,
  isclear SMALLINT(8) UNSIGNED ZEROFILL DEFAULT 00000000,
  debitParterner VARCHAR(10) DEFAULT NULL,
  workdate DATETIME DEFAULT NULL,
  userid VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX UQ_t_nodeclass_detail_classNo (classNo),
  UNIQUE INDEX UQ_t_nodeclass_detail_id (id),
  CONSTRAINT t_nodeclass_detail_ibfk_1 FOREIGN KEY (classNo)
    REFERENCES t_nodeclass(classNo) ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 394
AVG_ROW_LENGTH = 269
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS t_parterner;
CREATE TABLE t_parterner(
  code VARCHAR(255) DEFAULT NULL,
  type INT(10) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  parternerId VARCHAR(50) DEFAULT NULL,
  telephone VARCHAR(255) DEFAULT NULL,
  relaperson VARCHAR(255) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  status INT(10) DEFAULT NULL,
  py VARCHAR(50) DEFAULT NULL
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `t_b_weixin`;
CREATE TABLE `t_b_weixin` (
  `id` varchar(50) NOT NULL COMMENT 'id',
  `branchid` varchar(50) NOT NULL,
  `appid` varchar(50) NOT NULL,
  `partner` varchar(50) NOT NULL,
  `appsecret` varchar(50) NOT NULL,
  `weixintype` int(11) DEFAULT NULL,
  `personweixinurl` varchar(100) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `t_b_weixin_temp`;
CREATE TABLE `t_b_weixin_temp` (
  `id` varchar(50) NOT NULL,
  `orderno` varchar(50) NOT NULL,
  `outorderno` varchar(50) NOT NULL,
  `status` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `t_billing_detail`;

CREATE TABLE `t_billing_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `orderid` varchar(50) NOT NULL COMMENT '订单编号',
  `branchid` varchar(50) NOT NULL COMMENT '分店ID',
  `creaditname` varchar(100) NOT NULL COMMENT '挂账单位名称',
  `payamount` decimal(8,2) DEFAULT NULL COMMENT '已结金额',
  `disamount` decimal(8,2) DEFAULT NULL COMMENT '优免金额',
  `operator` varchar(255) NOT NULL COMMENT '操作员',
  `inserttime` datetime NOT NULL COMMENT '操作时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=utf8 COMMENT='挂账信息结算历史表';

DROP TABLE IF EXISTS `t_b_tip`;

CREATE TABLE `t_b_tip` (
  `waiter_number` varchar(50) NOT NULL COMMENT '服务员编号',
  `receivables` int(11) NOT NULL COMMENT '应收金额',
  `paid` int(11) DEFAULT NULL COMMENT '实收金额',
  `orderid` varchar(50) NOT NULL COMMENT '订单编号',
  `insertime` datetime NOT NULL COMMENT '创建时间',
  `branchid` int(11) NOT NULL COMMENT '门店编号',
  PRIMARY KEY (`orderid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_printer_state`;
CREATE TABLE `t_printer_state` (
  `ip` varchar(15) NOT NULL DEFAULT '' COMMENT '打印机IP 主键',
  `workstatus` smallint(6) DEFAULT '1' COMMENT '打印机状态',
  PRIMARY KEY (`ip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_device`;
CREATE TABLE `t_device` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `device_group` VARCHAR(32) DEFAULT NULL COMMENT '组号',
  `device_id` VARCHAR(32) DEFAULT NULL COMMENT '组id',
  `device_type` VARCHAR(255) DEFAULT NULL COMMENT '设备类型',
  `meid` VARCHAR(32) DEFAULT NULL COMMENT 'meid',
  `ss_id` VARCHAR(32) DEFAULT NULL COMMENT 'ssid',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `valid_flag` INT(11) DEFAULT NULL COMMENT '是否有效',
  PRIMARY KEY (`id`),
  KEY `group_id` (`device_group`,`device_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `t_offline_msg`;
CREATE TABLE `t_offline_msg` (
  `id` VARCHAR(64) NOT NULL,
  `msg_type` VARCHAR(32) DEFAULT NULL COMMENT '消息类型',
  `content` TEXT COMMENT '消息内容',
  `device_group` VARCHAR(255) DEFAULT NULL COMMENT '设备组',
  `device_id` VARCHAR(32) DEFAULT NULL COMMENT '设备id',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `expire_time` DATETIME DEFAULT NULL COMMENT '过期时间',
  `is_single` INT(11) DEFAULT NULL COMMENT '是否互斥',
  PRIMARY KEY (`id`),
  KEY `group_id` (`device_group`,`device_id`),
  KEY `expire_time` (`expire_time`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_b_padconfig`;
CREATE TABLE `t_b_padconfig` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `padloginpass` varchar(20) DEFAULT NULL,
  `social` tinyint(1) DEFAULT NULL,
  `seatimageurls` varchar(500) DEFAULT NULL,
  `seatimagenames` varchar(100) DEFAULT NULL,
  `vipstatus` tinyint(1) DEFAULT NULL,
  `viptype` varchar(8) DEFAULT NULL,
  `vipcandaourl` varchar(50) DEFAULT NULL,
  `vipotherurl` varchar(50) DEFAULT NULL,
  `clickimagedish` tinyint(1) DEFAULT NULL,
  `onepage` tinyint(1) DEFAULT NULL,
  `newplayer` tinyint(1) DEFAULT NULL,
  `chinaEnglish` tinyint(1) DEFAULT NULL,
  `indexad` tinyint(1) DEFAULT NULL,
  `invoice` tinyint(1) DEFAULT NULL,
  `hidecarttotal` tinyint(1) DEFAULT NULL,
  `adtimes` varchar(10) DEFAULT NULL,
  `waiterreward` tinyint(1) DEFAULT NULL,
  `rewardmoney` varchar(10) DEFAULT NULL,
  `youmengappkey` varchar(150) DEFAULT NULL,
  `youmengchinnal` varchar(150) DEFAULT NULL,
  `bigdatainterface` varchar(150) DEFAULT NULL,
  `braceletgappkey` varchar(150) DEFAULT NULL,
  `braceletchinnal` varchar(150) DEFAULT NULL,
  `weixintype` varchar(8) DEFAULT NULL,
  `personweixinurl` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_order_detail_preferential
-- ----------------------------
DROP TABLE IF EXISTS `t_order_detail_preferential`;
CREATE TABLE `t_order_detail_preferential` (
  `id` varchar(50) NOT NULL COMMENT 'UUID主键由门店后台生成',
  `orderid` varchar(50) NOT NULL COMMENT '订单号',
  `dishid` varchar(50) DEFAULT NULL COMMENT '菜品编号',
  `dishNum` varchar(20) NOT NULL COMMENT '菜品数量',
  `preferential` varchar(50) NOT NULL COMMENT '优惠表主键',
  `deAmount` decimal(30,7) DEFAULT '1.0000000' COMMENT '使用优惠卷张数',
  `discount` decimal(6,4) DEFAULT '0.0000' COMMENT '折扣信息',
  `isCustom` tinyint(1) DEFAULT '0' COMMENT '是否是自己设定',
  `isGroup` tinyint(1) DEFAULT '0' COMMENT '是否是全局使用优惠',
  `isUse` tinyint(1) DEFAULT '1' COMMENT '当前菜单对应的优惠卷是否使用中（1使用0菜品被删除）',
  `toalFreeAmount` decimal(10,4) DEFAULT NULL COMMENT '优免总金额',
  `toalDebitAmount` decimal(10,4) DEFAULT NULL COMMENT '挂账总金额',
  `insertime` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '当前插入时间',
  `unit` varchar(50) DEFAULT NULL COMMENT '菜品单位',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for `t_printer_device`
-- ----------------------------
DROP TABLE IF EXISTS `t_printer_device`;
CREATE TABLE `t_printer_device` (
  `deviceid` varchar(50) NOT NULL,
  `devicecode` varchar(50) NOT NULL COMMENT '设备编码 唯一',
  `devicename` varchar(50) DEFAULT NULL COMMENT '设备名称',
  `devicearea` varchar(50) DEFAULT NULL COMMENT '设备所属区域',
  `devicestatus` int(11) DEFAULT NULL COMMENT '设备状态',
  `devicetype` int(11) DEFAULT NULL COMMENT '设备类型',
  `deviceip` varchar(50) DEFAULT NULL COMMENT '设备IP',
  `inserttime` datetime DEFAULT NULL COMMENT '插入时间',
  `modifiedtime` datetime DEFAULT NULL COMMENT '修改时间',
  `deviceowner` varchar(50) DEFAULT NULL COMMENT '设备所属',
  `devicegroup` varchar(50) DEFAULT NULL COMMENT '设备所属组',
  PRIMARY KEY (`deviceid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;

-- ----------------------------
-- Table structure for `t_printer_deviceprinter`
-- ----------------------------
DROP TABLE IF EXISTS `t_printer_deviceprinter`;
CREATE TABLE `t_printer_deviceprinter` (
  `id` varchar(50) NOT NULL COMMENT '设备主键',
  `devicecode` varchar(50) DEFAULT NULL COMMENT '设备编码 唯一',
  `devicename` varchar(50) DEFAULT NULL COMMENT '设备名称',
  `printerid` varchar(50) DEFAULT NULL COMMENT '打印机IP',
  `printername` varchar(50) DEFAULT NULL COMMENT '打印机名称',
  `printerip` varchar(50) DEFAULT NULL COMMENT '打印机ip',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `t_dish_sellout`;
CREATE TABLE `t_dish_sellout` (
  `id` int(50) NOT NULL AUTO_INCREMENT,
  `dishid` varchar(50) DEFAULT NULL,
  `dishunit` varchar(255) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
